// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 0fa45fbca4a33a4325bee1177c75f22c465e294e

package rpc

import (
	"context"
	"encoding/json"

	"github.com/pmenglund/codex-sdk-go/protocol"
)

// ClientRequests exposes typed JSON-RPC calls supported by the app-server.
type ClientRequests interface {
	AccountLoginCancel(ctx context.Context, params protocol.CancelLoginAccountParams) (*protocol.CancelLoginAccountResponse, error)
	AccountLoginStart(ctx context.Context, params protocol.LoginAccountParams) (*protocol.LoginAccountResponse, error)
	AccountLogout(ctx context.Context) (*protocol.LogoutAccountResponse, error)
	AccountRateLimitsRead(ctx context.Context) (*protocol.GetAccountRateLimitsResponse, error)
	AccountRead(ctx context.Context, params protocol.GetAccountParams) (*protocol.GetAccountResponse, error)
	AddConversationListener(ctx context.Context, params protocol.AddConversationListenerParams) (*protocol.AddConversationSubscriptionResponse, error)
	AppList(ctx context.Context, params protocol.AppsListParams) (*protocol.AppsListResponse, error)
	ArchiveConversation(ctx context.Context, params protocol.ArchiveConversationParams) (*protocol.ArchiveConversationResponse, error)
	CancelLoginChatGpt(ctx context.Context, params protocol.CancelLoginChatGptParams) (*protocol.CancelLoginChatGptResponse, error)
	CollaborationModeList(ctx context.Context, params protocol.CollaborationModeListParams) (*protocol.CollaborationModeListResponse, error)
	CommandExec(ctx context.Context, params protocol.CommandExecParams) (*protocol.CommandExecResponse, error)
	ConfigBatchWrite(ctx context.Context, params protocol.ConfigBatchWriteParams) (*protocol.ConfigWriteResponse, error)
	ConfigMcpServerReload(ctx context.Context) (*protocol.McpServerRefreshResponse, error)
	ConfigRead(ctx context.Context, params protocol.ConfigReadParams) (*protocol.ConfigReadResponse, error)
	ConfigValueWrite(ctx context.Context, params protocol.ConfigValueWriteParams) (*protocol.ConfigWriteResponse, error)
	ConfigRequirementsRead(ctx context.Context) (*protocol.ConfigRequirementsReadResponse, error)
	ExecOneOffCommand(ctx context.Context, params protocol.ExecOneOffCommandParams) (*protocol.ExecOneOffCommandResponse, error)
	FeedbackUpload(ctx context.Context, params protocol.FeedbackUploadParams) (*protocol.FeedbackUploadResponse, error)
	ForkConversation(ctx context.Context, params protocol.ForkConversationParams) (*protocol.ForkConversationResponse, error)
	FuzzyFileSearch(ctx context.Context, params protocol.FuzzyFileSearchParams) (*protocol.FuzzyFileSearchResponse, error)
	GetAuthStatus(ctx context.Context, params protocol.GetAuthStatusParams) (*protocol.GetAuthStatusResponse, error)
	GetConversationSummary(ctx context.Context, params protocol.GetConversationSummaryParams) (*protocol.GetConversationSummaryResponse, error)
	GetUserAgent(ctx context.Context) (*protocol.GetUserAgentResponse, error)
	GetUserSavedConfig(ctx context.Context) (*protocol.GetUserSavedConfigResponse, error)
	GitDiffToRemote(ctx context.Context, params protocol.GitDiffToRemoteParams) (*protocol.GitDiffToRemoteResponse, error)
	Initialize(ctx context.Context, params protocol.InitializeParams) (*protocol.InitializeResponse, error)
	InterruptConversation(ctx context.Context, params protocol.InterruptConversationParams) (*protocol.InterruptConversationResponse, error)
	ListConversations(ctx context.Context, params protocol.ListConversationsParams) (*protocol.ListConversationsResponse, error)
	LoginApiKey(ctx context.Context, params protocol.LoginApiKeyParams) (*protocol.LoginApiKeyResponse, error)
	LoginChatGpt(ctx context.Context) (*protocol.LoginChatGptResponse, error)
	LogoutChatGpt(ctx context.Context) (*protocol.LogoutChatGptResponse, error)
	McpServerOauthLogin(ctx context.Context, params protocol.McpServerOauthLoginParams) (*protocol.McpServerOauthLoginResponse, error)
	McpServerStatusList(ctx context.Context, params protocol.ListMcpServerStatusParams) (*protocol.ListMcpServerStatusResponse, error)
	ModelList(ctx context.Context, params protocol.ModelListParams) (*protocol.ModelListResponse, error)
	NewConversation(ctx context.Context, params protocol.NewConversationParams) (*protocol.NewConversationResponse, error)
	RemoveConversationListener(ctx context.Context, params protocol.RemoveConversationListenerParams) (*protocol.RemoveConversationSubscriptionResponse, error)
	ResumeConversation(ctx context.Context, params protocol.ResumeConversationParams) (*protocol.ResumeConversationResponse, error)
	ReviewStart(ctx context.Context, params protocol.ReviewStartParams) (*protocol.ReviewStartResponse, error)
	SendUserMessage(ctx context.Context, params protocol.SendUserMessageParams) (*protocol.SendUserMessageResponse, error)
	SendUserTurn(ctx context.Context, params protocol.SendUserTurnParams) (*protocol.SendUserTurnResponse, error)
	SetDefaultModel(ctx context.Context, params protocol.SetDefaultModelParams) (*protocol.SetDefaultModelResponse, error)
	SkillsConfigWrite(ctx context.Context, params protocol.SkillsConfigWriteParams) (*protocol.SkillsConfigWriteResponse, error)
	SkillsList(ctx context.Context, params protocol.SkillsListParams) (*protocol.SkillsListResponse, error)
	ThreadArchive(ctx context.Context, params protocol.ThreadArchiveParams) (*protocol.ThreadArchiveResponse, error)
	ThreadFork(ctx context.Context, params protocol.ThreadForkParams) (*protocol.ThreadForkResponse, error)
	ThreadList(ctx context.Context, params protocol.ThreadListParams) (*protocol.ThreadListResponse, error)
	ThreadLoadedList(ctx context.Context, params protocol.ThreadLoadedListParams) (*protocol.ThreadLoadedListResponse, error)
	ThreadRead(ctx context.Context, params protocol.ThreadReadParams) (*protocol.ThreadReadResponse, error)
	ThreadResume(ctx context.Context, params protocol.ThreadResumeParams) (*protocol.ThreadResumeResponse, error)
	ThreadRollback(ctx context.Context, params protocol.ThreadRollbackParams) (*protocol.ThreadRollbackResponse, error)
	ThreadStart(ctx context.Context, params protocol.ThreadStartParams) (*protocol.ThreadStartResponse, error)
	TurnInterrupt(ctx context.Context, params protocol.TurnInterruptParams) (*protocol.TurnInterruptResponse, error)
	TurnStart(ctx context.Context, params protocol.TurnStartParams) (*protocol.TurnStartResponse, error)
	UserInfo(ctx context.Context) (*protocol.UserInfoResponse, error)
}

// Client implements ClientRequests using JSON-RPC.
func (c *Client) AccountLoginCancel(ctx context.Context, params protocol.CancelLoginAccountParams) (*protocol.CancelLoginAccountResponse, error) {
	var result protocol.CancelLoginAccountResponse
	if err := c.Call(ctx, "account/login/cancel", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountLoginStart(ctx context.Context, params protocol.LoginAccountParams) (*protocol.LoginAccountResponse, error) {
	var result protocol.LoginAccountResponse
	if err := c.Call(ctx, "account/login/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountLogout(ctx context.Context) (*protocol.LogoutAccountResponse, error) {
	var result protocol.LogoutAccountResponse
	if err := c.Call(ctx, "account/logout", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountRateLimitsRead(ctx context.Context) (*protocol.GetAccountRateLimitsResponse, error) {
	var result protocol.GetAccountRateLimitsResponse
	if err := c.Call(ctx, "account/rateLimits/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountRead(ctx context.Context, params protocol.GetAccountParams) (*protocol.GetAccountResponse, error) {
	var result protocol.GetAccountResponse
	if err := c.Call(ctx, "account/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AddConversationListener(ctx context.Context, params protocol.AddConversationListenerParams) (*protocol.AddConversationSubscriptionResponse, error) {
	var result protocol.AddConversationSubscriptionResponse
	if err := c.Call(ctx, "addConversationListener", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AppList(ctx context.Context, params protocol.AppsListParams) (*protocol.AppsListResponse, error) {
	var result protocol.AppsListResponse
	if err := c.Call(ctx, "app/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ArchiveConversation(ctx context.Context, params protocol.ArchiveConversationParams) (*protocol.ArchiveConversationResponse, error) {
	var result protocol.ArchiveConversationResponse
	if err := c.Call(ctx, "archiveConversation", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CancelLoginChatGpt(ctx context.Context, params protocol.CancelLoginChatGptParams) (*protocol.CancelLoginChatGptResponse, error) {
	var result protocol.CancelLoginChatGptResponse
	if err := c.Call(ctx, "cancelLoginChatGpt", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CollaborationModeList(ctx context.Context, params protocol.CollaborationModeListParams) (*protocol.CollaborationModeListResponse, error) {
	var result protocol.CollaborationModeListResponse
	if err := c.Call(ctx, "collaborationMode/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExec(ctx context.Context, params protocol.CommandExecParams) (*protocol.CommandExecResponse, error) {
	var result protocol.CommandExecResponse
	if err := c.Call(ctx, "command/exec", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigBatchWrite(ctx context.Context, params protocol.ConfigBatchWriteParams) (*protocol.ConfigWriteResponse, error) {
	var result protocol.ConfigWriteResponse
	if err := c.Call(ctx, "config/batchWrite", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigMcpServerReload(ctx context.Context) (*protocol.McpServerRefreshResponse, error) {
	var result protocol.McpServerRefreshResponse
	if err := c.Call(ctx, "config/mcpServer/reload", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigRead(ctx context.Context, params protocol.ConfigReadParams) (*protocol.ConfigReadResponse, error) {
	var result protocol.ConfigReadResponse
	if err := c.Call(ctx, "config/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigValueWrite(ctx context.Context, params protocol.ConfigValueWriteParams) (*protocol.ConfigWriteResponse, error) {
	var result protocol.ConfigWriteResponse
	if err := c.Call(ctx, "config/value/write", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigRequirementsRead(ctx context.Context) (*protocol.ConfigRequirementsReadResponse, error) {
	var result protocol.ConfigRequirementsReadResponse
	if err := c.Call(ctx, "configRequirements/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExecOneOffCommand(ctx context.Context, params protocol.ExecOneOffCommandParams) (*protocol.ExecOneOffCommandResponse, error) {
	var result protocol.ExecOneOffCommandResponse
	if err := c.Call(ctx, "execOneOffCommand", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FeedbackUpload(ctx context.Context, params protocol.FeedbackUploadParams) (*protocol.FeedbackUploadResponse, error) {
	var result protocol.FeedbackUploadResponse
	if err := c.Call(ctx, "feedback/upload", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ForkConversation(ctx context.Context, params protocol.ForkConversationParams) (*protocol.ForkConversationResponse, error) {
	var result protocol.ForkConversationResponse
	if err := c.Call(ctx, "forkConversation", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FuzzyFileSearch(ctx context.Context, params protocol.FuzzyFileSearchParams) (*protocol.FuzzyFileSearchResponse, error) {
	var result protocol.FuzzyFileSearchResponse
	if err := c.Call(ctx, "fuzzyFileSearch", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) GetAuthStatus(ctx context.Context, params protocol.GetAuthStatusParams) (*protocol.GetAuthStatusResponse, error) {
	var result protocol.GetAuthStatusResponse
	if err := c.Call(ctx, "getAuthStatus", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) GetConversationSummary(ctx context.Context, params protocol.GetConversationSummaryParams) (*protocol.GetConversationSummaryResponse, error) {
	var result protocol.GetConversationSummaryResponse
	if err := c.Call(ctx, "getConversationSummary", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) GetUserAgent(ctx context.Context) (*protocol.GetUserAgentResponse, error) {
	var result protocol.GetUserAgentResponse
	if err := c.Call(ctx, "getUserAgent", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) GetUserSavedConfig(ctx context.Context) (*protocol.GetUserSavedConfigResponse, error) {
	var result protocol.GetUserSavedConfigResponse
	if err := c.Call(ctx, "getUserSavedConfig", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) GitDiffToRemote(ctx context.Context, params protocol.GitDiffToRemoteParams) (*protocol.GitDiffToRemoteResponse, error) {
	var result protocol.GitDiffToRemoteResponse
	if err := c.Call(ctx, "gitDiffToRemote", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) Initialize(ctx context.Context, params protocol.InitializeParams) (*protocol.InitializeResponse, error) {
	var result protocol.InitializeResponse
	if err := c.Call(ctx, "initialize", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) InterruptConversation(ctx context.Context, params protocol.InterruptConversationParams) (*protocol.InterruptConversationResponse, error) {
	var result protocol.InterruptConversationResponse
	if err := c.Call(ctx, "interruptConversation", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ListConversations(ctx context.Context, params protocol.ListConversationsParams) (*protocol.ListConversationsResponse, error) {
	var result protocol.ListConversationsResponse
	if err := c.Call(ctx, "listConversations", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) LoginApiKey(ctx context.Context, params protocol.LoginApiKeyParams) (*protocol.LoginApiKeyResponse, error) {
	var result protocol.LoginApiKeyResponse
	if err := c.Call(ctx, "loginApiKey", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) LoginChatGpt(ctx context.Context) (*protocol.LoginChatGptResponse, error) {
	var result protocol.LoginChatGptResponse
	if err := c.Call(ctx, "loginChatGpt", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) LogoutChatGpt(ctx context.Context) (*protocol.LogoutChatGptResponse, error) {
	var result protocol.LogoutChatGptResponse
	if err := c.Call(ctx, "logoutChatGpt", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) McpServerOauthLogin(ctx context.Context, params protocol.McpServerOauthLoginParams) (*protocol.McpServerOauthLoginResponse, error) {
	var result protocol.McpServerOauthLoginResponse
	if err := c.Call(ctx, "mcpServer/oauth/login", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) McpServerStatusList(ctx context.Context, params protocol.ListMcpServerStatusParams) (*protocol.ListMcpServerStatusResponse, error) {
	var result protocol.ListMcpServerStatusResponse
	if err := c.Call(ctx, "mcpServerStatus/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ModelList(ctx context.Context, params protocol.ModelListParams) (*protocol.ModelListResponse, error) {
	var result protocol.ModelListResponse
	if err := c.Call(ctx, "model/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) NewConversation(ctx context.Context, params protocol.NewConversationParams) (*protocol.NewConversationResponse, error) {
	var result protocol.NewConversationResponse
	if err := c.Call(ctx, "newConversation", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RemoveConversationListener(ctx context.Context, params protocol.RemoveConversationListenerParams) (*protocol.RemoveConversationSubscriptionResponse, error) {
	var result protocol.RemoveConversationSubscriptionResponse
	if err := c.Call(ctx, "removeConversationListener", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ResumeConversation(ctx context.Context, params protocol.ResumeConversationParams) (*protocol.ResumeConversationResponse, error) {
	var result protocol.ResumeConversationResponse
	if err := c.Call(ctx, "resumeConversation", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ReviewStart(ctx context.Context, params protocol.ReviewStartParams) (*protocol.ReviewStartResponse, error) {
	var result protocol.ReviewStartResponse
	if err := c.Call(ctx, "review/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SendUserMessage(ctx context.Context, params protocol.SendUserMessageParams) (*protocol.SendUserMessageResponse, error) {
	var result protocol.SendUserMessageResponse
	if err := c.Call(ctx, "sendUserMessage", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SendUserTurn(ctx context.Context, params protocol.SendUserTurnParams) (*protocol.SendUserTurnResponse, error) {
	var result protocol.SendUserTurnResponse
	if err := c.Call(ctx, "sendUserTurn", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SetDefaultModel(ctx context.Context, params protocol.SetDefaultModelParams) (*protocol.SetDefaultModelResponse, error) {
	var result protocol.SetDefaultModelResponse
	if err := c.Call(ctx, "setDefaultModel", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SkillsConfigWrite(ctx context.Context, params protocol.SkillsConfigWriteParams) (*protocol.SkillsConfigWriteResponse, error) {
	var result protocol.SkillsConfigWriteResponse
	if err := c.Call(ctx, "skills/config/write", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SkillsList(ctx context.Context, params protocol.SkillsListParams) (*protocol.SkillsListResponse, error) {
	var result protocol.SkillsListResponse
	if err := c.Call(ctx, "skills/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadArchive(ctx context.Context, params protocol.ThreadArchiveParams) (*protocol.ThreadArchiveResponse, error) {
	var result protocol.ThreadArchiveResponse
	if err := c.Call(ctx, "thread/archive", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadFork(ctx context.Context, params protocol.ThreadForkParams) (*protocol.ThreadForkResponse, error) {
	var result protocol.ThreadForkResponse
	if err := c.Call(ctx, "thread/fork", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadList(ctx context.Context, params protocol.ThreadListParams) (*protocol.ThreadListResponse, error) {
	var result protocol.ThreadListResponse
	if err := c.Call(ctx, "thread/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadLoadedList(ctx context.Context, params protocol.ThreadLoadedListParams) (*protocol.ThreadLoadedListResponse, error) {
	var result protocol.ThreadLoadedListResponse
	if err := c.Call(ctx, "thread/loaded/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadRead(ctx context.Context, params protocol.ThreadReadParams) (*protocol.ThreadReadResponse, error) {
	var result protocol.ThreadReadResponse
	if err := c.Call(ctx, "thread/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadResume(ctx context.Context, params protocol.ThreadResumeParams) (*protocol.ThreadResumeResponse, error) {
	var result protocol.ThreadResumeResponse
	if err := c.Call(ctx, "thread/resume", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadRollback(ctx context.Context, params protocol.ThreadRollbackParams) (*protocol.ThreadRollbackResponse, error) {
	var result protocol.ThreadRollbackResponse
	if err := c.Call(ctx, "thread/rollback", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadStart(ctx context.Context, params protocol.ThreadStartParams) (*protocol.ThreadStartResponse, error) {
	var result protocol.ThreadStartResponse
	if err := c.Call(ctx, "thread/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) TurnInterrupt(ctx context.Context, params protocol.TurnInterruptParams) (*protocol.TurnInterruptResponse, error) {
	var result protocol.TurnInterruptResponse
	if err := c.Call(ctx, "turn/interrupt", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) TurnStart(ctx context.Context, params protocol.TurnStartParams) (*protocol.TurnStartResponse, error) {
	var result protocol.TurnStartResponse
	if err := c.Call(ctx, "turn/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) UserInfo(ctx context.Context) (*protocol.UserInfoResponse, error) {
	var result protocol.UserInfoResponse
	if err := c.Call(ctx, "userInfo", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BuildClientRequest builds a JSON-RPC request for a client method.
func BuildClientRequest(method string, params any, id RequestID) (JSONRPCRequest, error) {
	var raw json.RawMessage
	if params != nil {
		data, err := json.Marshal(params)
		if err != nil {
			return JSONRPCRequest{}, err
		}
		raw = data
	}
	return JSONRPCRequest{ID: id, Method: method, Params: raw}, nil
}
