// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: be6e8eac029b183056b7e4402879f15d2c85f61b

package rpc

import (
	"context"
	"encoding/json"

	"github.com/pmenglund/codex-sdk-go/protocol"
)

// ClientRequests exposes every generated JSON-RPC call supported by the app-server.
//
// Deprecated: define a narrow interface containing only the methods your code consumes.
type ClientRequests interface {
	AccountLoginCancel(ctx context.Context, params protocol.CancelLoginAccountParams) (*protocol.CancelLoginAccountResponse, error)
	AccountLoginStart(ctx context.Context, params protocol.LoginAccountParams) (*protocol.LoginAccountResponse, error)
	AccountLogout(ctx context.Context) (*protocol.LogoutAccountResponse, error)
	AccountRateLimitResetCreditConsume(ctx context.Context, params protocol.ConsumeAccountRateLimitResetCreditParams) (*protocol.ConsumeAccountRateLimitResetCreditResponse, error)
	AccountRateLimitsRead(ctx context.Context) (*protocol.GetAccountRateLimitsResponse, error)
	AccountRead(ctx context.Context, params protocol.GetAccountParams) (*protocol.GetAccountResponse, error)
	AccountSendAddCreditsNudgeEmail(ctx context.Context, params protocol.SendAddCreditsNudgeEmailParams) (*protocol.SendAddCreditsNudgeEmailResponse, error)
	AccountUsageRead(ctx context.Context) (*protocol.GetAccountTokenUsageResponse, error)
	AccountWorkspaceMessagesRead(ctx context.Context) (*protocol.GetWorkspaceMessagesResponse, error)
	AppInstalled(ctx context.Context, params protocol.AppsInstalledParams) (*protocol.AppsInstalledResponse, error)
	AppList(ctx context.Context, params protocol.AppsListParams) (*protocol.AppsListResponse, error)
	AppRead(ctx context.Context, params protocol.AppsReadParams) (*protocol.AppsReadResponse, error)
	CommandExec(ctx context.Context, params protocol.CommandExecParams) (*protocol.CommandExecResponse, error)
	CommandExecResize(ctx context.Context, params protocol.CommandExecResizeParams) (*protocol.CommandExecResizeResponse, error)
	CommandExecTerminate(ctx context.Context, params protocol.CommandExecTerminateParams) (*protocol.CommandExecTerminateResponse, error)
	CommandExecWrite(ctx context.Context, params protocol.CommandExecWriteParams) (*protocol.CommandExecWriteResponse, error)
	ConfigBatchWrite(ctx context.Context, params protocol.ConfigBatchWriteParams) (*protocol.ConfigWriteResponse, error)
	ConfigMCPServerReload(ctx context.Context) (*protocol.MCPServerRefreshResponse, error)
	ConfigRead(ctx context.Context, params protocol.ConfigReadParams) (*protocol.ConfigReadResponse, error)
	ConfigValueWrite(ctx context.Context, params protocol.ConfigValueWriteParams) (*protocol.ConfigWriteResponse, error)
	ConfigRequirementsRead(ctx context.Context) (*protocol.ConfigRequirementsReadResponse, error)
	ExperimentalFeatureEnablementSet(ctx context.Context, params protocol.ExperimentalFeatureEnablementSetParams) (*protocol.ExperimentalFeatureEnablementSetResponse, error)
	ExperimentalFeatureList(ctx context.Context, params protocol.ExperimentalFeatureListParams) (*protocol.ExperimentalFeatureListResponse, error)
	ExternalAgentConfigDetect(ctx context.Context, params protocol.ExternalAgentConfigDetectParams) (*protocol.ExternalAgentConfigDetectResponse, error)
	ExternalAgentConfigImport(ctx context.Context, params protocol.ExternalAgentConfigImportParams) (*protocol.ExternalAgentConfigImportResponse, error)
	ExternalAgentConfigImportReadHistories(ctx context.Context) (*protocol.ExternalAgentConfigImportHistoriesReadResponse, error)
	ExternalAgentConfigImportRecordHistory(ctx context.Context, params protocol.ExternalAgentConfigImportHistoryRecordParams) (*protocol.ExternalAgentConfigImportHistoryRecordResponse, error)
	FeedbackUpload(ctx context.Context, params protocol.FeedbackUploadParams) (*protocol.FeedbackUploadResponse, error)
	FsCopy(ctx context.Context, params protocol.FsCopyParams) (*protocol.FsCopyResponse, error)
	FsCreateDirectory(ctx context.Context, params protocol.FsCreateDirectoryParams) (*protocol.FsCreateDirectoryResponse, error)
	FsGetMetadata(ctx context.Context, params protocol.FsGetMetadataParams) (*protocol.FsGetMetadataResponse, error)
	FsReadDirectory(ctx context.Context, params protocol.FsReadDirectoryParams) (*protocol.FsReadDirectoryResponse, error)
	FsReadFile(ctx context.Context, params protocol.FsReadFileParams) (*protocol.FsReadFileResponse, error)
	FsRemove(ctx context.Context, params protocol.FsRemoveParams) (*protocol.FsRemoveResponse, error)
	FsUnwatch(ctx context.Context, params protocol.FsUnwatchParams) (*protocol.FsUnwatchResponse, error)
	FsWatch(ctx context.Context, params protocol.FsWatchParams) (*protocol.FsWatchResponse, error)
	FsWriteFile(ctx context.Context, params protocol.FsWriteFileParams) (*protocol.FsWriteFileResponse, error)
	FuzzyFileSearch(ctx context.Context, params protocol.FuzzyFileSearchParams) (*protocol.FuzzyFileSearchResponse, error)
	HooksList(ctx context.Context, params protocol.HooksListParams) (*protocol.HooksListResponse, error)
	Initialize(ctx context.Context, params protocol.InitializeParams) (*protocol.InitializeResponse, error)
	MarketplaceAdd(ctx context.Context, params protocol.MarketplaceAddParams) (*protocol.MarketplaceAddResponse, error)
	MarketplaceRemove(ctx context.Context, params protocol.MarketplaceRemoveParams) (*protocol.MarketplaceRemoveResponse, error)
	MarketplaceUpgrade(ctx context.Context, params protocol.MarketplaceUpgradeParams) (*protocol.MarketplaceUpgradeResponse, error)
	MCPServerOAuthLogin(ctx context.Context, params protocol.MCPServerOAuthLoginParams) (*protocol.MCPServerOAuthLoginResponse, error)
	MCPServerResourceRead(ctx context.Context, params protocol.MCPResourceReadParams) (*protocol.MCPResourceReadResponse, error)
	MCPServerToolCall(ctx context.Context, params protocol.MCPServerToolCallParams) (*protocol.MCPServerToolCallResponse, error)
	MCPServerStatusList(ctx context.Context, params protocol.ListMCPServerStatusParams) (*protocol.ListMCPServerStatusResponse, error)
	ModelList(ctx context.Context, params protocol.ModelListParams) (*protocol.ModelListResponse, error)
	ModelProviderCapabilitiesRead(ctx context.Context, params protocol.ModelProviderCapabilitiesReadParams) (*protocol.ModelProviderCapabilitiesReadResponse, error)
	PermissionProfileList(ctx context.Context, params protocol.PermissionProfileListParams) (*protocol.PermissionProfileListResponse, error)
	PluginInstall(ctx context.Context, params protocol.PluginInstallParams) (*protocol.PluginInstallResponse, error)
	PluginInstalled(ctx context.Context, params protocol.PluginInstalledParams) (*protocol.PluginInstalledResponse, error)
	PluginList(ctx context.Context, params protocol.PluginListParams) (*protocol.PluginListResponse, error)
	PluginRead(ctx context.Context, params protocol.PluginReadParams) (*protocol.PluginReadResponse, error)
	PluginShareCheckout(ctx context.Context, params protocol.PluginShareCheckoutParams) (*protocol.PluginShareCheckoutResponse, error)
	PluginShareDelete(ctx context.Context, params protocol.PluginShareDeleteParams) (*protocol.PluginShareDeleteResponse, error)
	PluginShareList(ctx context.Context, params protocol.PluginShareListParams) (*protocol.PluginShareListResponse, error)
	PluginShareSave(ctx context.Context, params protocol.PluginShareSaveParams) (*protocol.PluginShareSaveResponse, error)
	PluginShareUpdateTargets(ctx context.Context, params protocol.PluginShareUpdateTargetsParams) (*protocol.PluginShareUpdateTargetsResponse, error)
	PluginSkillRead(ctx context.Context, params protocol.PluginSkillReadParams) (*protocol.PluginSkillReadResponse, error)
	PluginUninstall(ctx context.Context, params protocol.PluginUninstallParams) (*protocol.PluginUninstallResponse, error)
	ReviewStart(ctx context.Context, params protocol.ReviewStartParams) (*protocol.ReviewStartResponse, error)
	SkillsConfigWrite(ctx context.Context, params protocol.SkillsConfigWriteParams) (*protocol.SkillsConfigWriteResponse, error)
	SkillsExtraRootsSet(ctx context.Context, params protocol.SkillsExtraRootsSetParams) (*protocol.SkillsExtraRootsSetResponse, error)
	SkillsList(ctx context.Context, params protocol.SkillsListParams) (*protocol.SkillsListResponse, error)
	ThreadApproveGuardianDeniedAction(ctx context.Context, params protocol.ThreadApproveGuardianDeniedActionParams) (*protocol.ThreadApproveGuardianDeniedActionResponse, error)
	ThreadArchive(ctx context.Context, params protocol.ThreadArchiveParams) (*protocol.ThreadArchiveResponse, error)
	ThreadCompactStart(ctx context.Context, params protocol.ThreadCompactStartParams) (*protocol.ThreadCompactStartResponse, error)
	ThreadDelete(ctx context.Context, params protocol.ThreadDeleteParams) (*protocol.ThreadDeleteResponse, error)
	ThreadFork(ctx context.Context, params protocol.ThreadForkParams) (*protocol.ThreadForkResponse, error)
	ThreadGoalClear(ctx context.Context, params protocol.ThreadGoalClearParams) (*protocol.ThreadGoalClearResponse, error)
	ThreadGoalGet(ctx context.Context, params protocol.ThreadGoalGetParams) (*protocol.ThreadGoalGetResponse, error)
	ThreadGoalSet(ctx context.Context, params protocol.ThreadGoalSetParams) (*protocol.ThreadGoalSetResponse, error)
	ThreadInjectItems(ctx context.Context, params protocol.ThreadInjectItemsParams) (*protocol.ThreadInjectItemsResponse, error)
	ThreadList(ctx context.Context, params protocol.ThreadListParams) (*protocol.ThreadListResponse, error)
	ThreadLoadedList(ctx context.Context, params protocol.ThreadLoadedListParams) (*protocol.ThreadLoadedListResponse, error)
	ThreadMetadataUpdate(ctx context.Context, params protocol.ThreadMetadataUpdateParams) (*protocol.ThreadMetadataUpdateResponse, error)
	ThreadNameSet(ctx context.Context, params protocol.ThreadSetNameParams) (*protocol.ThreadSetNameResponse, error)
	ThreadRead(ctx context.Context, params protocol.ThreadReadParams) (*protocol.ThreadReadResponse, error)
	ThreadResume(ctx context.Context, params protocol.ThreadResumeParams) (*protocol.ThreadResumeResponse, error)
	ThreadRollback(ctx context.Context, params protocol.ThreadRollbackParams) (*protocol.ThreadRollbackResponse, error)
	ThreadSectionMove(ctx context.Context, params protocol.ThreadSectionMoveParams) (*protocol.ThreadSectionMoveResponse, error)
	ThreadShellCommand(ctx context.Context, params protocol.ThreadShellCommandParams) (*protocol.ThreadShellCommandResponse, error)
	ThreadStart(ctx context.Context, params protocol.ThreadStartParams) (*protocol.ThreadStartResponse, error)
	ThreadUnarchive(ctx context.Context, params protocol.ThreadUnarchiveParams) (*protocol.ThreadUnarchiveResponse, error)
	ThreadUnsubscribe(ctx context.Context, params protocol.ThreadUnsubscribeParams) (*protocol.ThreadUnsubscribeResponse, error)
	ThreadSectionCreate(ctx context.Context, params protocol.ThreadSectionCreateParams) (*protocol.ThreadSectionCreateResponse, error)
	ThreadSectionDelete(ctx context.Context, params protocol.ThreadSectionDeleteParams) (*protocol.ThreadSectionDeleteResponse, error)
	ThreadSectionList(ctx context.Context, params protocol.ThreadSectionListParams) (*protocol.ThreadSectionListResponse, error)
	ThreadSectionUpdate(ctx context.Context, params protocol.ThreadSectionUpdateParams) (*protocol.ThreadSectionUpdateResponse, error)
	TurnInterrupt(ctx context.Context, params protocol.TurnInterruptParams) (*protocol.TurnInterruptResponse, error)
	TurnStart(ctx context.Context, params protocol.TurnStartParams) (*protocol.TurnStartResponse, error)
	TurnSteer(ctx context.Context, params protocol.TurnSteerParams) (*protocol.TurnSteerResponse, error)
	WindowsSandboxReadiness(ctx context.Context) (*protocol.WindowsSandboxReadinessResponse, error)
	WindowsSandboxSetupStart(ctx context.Context, params protocol.WindowsSandboxSetupStartParams) (*protocol.WindowsSandboxSetupStartResponse, error)
}

// Client implements ClientRequests using JSON-RPC.
func (c *Client) AccountLoginCancel(ctx context.Context, params protocol.CancelLoginAccountParams) (*protocol.CancelLoginAccountResponse, error) {
	var result protocol.CancelLoginAccountResponse
	if err := c.Call(ctx, "account/login/cancel", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountLoginStart(ctx context.Context, params protocol.LoginAccountParams) (*protocol.LoginAccountResponse, error) {
	var result protocol.LoginAccountResponse
	if err := c.Call(ctx, "account/login/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountLogout(ctx context.Context) (*protocol.LogoutAccountResponse, error) {
	var result protocol.LogoutAccountResponse
	if err := c.Call(ctx, "account/logout", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountRateLimitResetCreditConsume(ctx context.Context, params protocol.ConsumeAccountRateLimitResetCreditParams) (*protocol.ConsumeAccountRateLimitResetCreditResponse, error) {
	var result protocol.ConsumeAccountRateLimitResetCreditResponse
	if err := c.Call(ctx, "account/rateLimitResetCredit/consume", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountRateLimitsRead(ctx context.Context) (*protocol.GetAccountRateLimitsResponse, error) {
	var result protocol.GetAccountRateLimitsResponse
	if err := c.Call(ctx, "account/rateLimits/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountRead(ctx context.Context, params protocol.GetAccountParams) (*protocol.GetAccountResponse, error) {
	var result protocol.GetAccountResponse
	if err := c.Call(ctx, "account/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountSendAddCreditsNudgeEmail(ctx context.Context, params protocol.SendAddCreditsNudgeEmailParams) (*protocol.SendAddCreditsNudgeEmailResponse, error) {
	var result protocol.SendAddCreditsNudgeEmailResponse
	if err := c.Call(ctx, "account/sendAddCreditsNudgeEmail", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountUsageRead(ctx context.Context) (*protocol.GetAccountTokenUsageResponse, error) {
	var result protocol.GetAccountTokenUsageResponse
	if err := c.Call(ctx, "account/usage/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AccountWorkspaceMessagesRead(ctx context.Context) (*protocol.GetWorkspaceMessagesResponse, error) {
	var result protocol.GetWorkspaceMessagesResponse
	if err := c.Call(ctx, "account/workspaceMessages/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AppInstalled(ctx context.Context, params protocol.AppsInstalledParams) (*protocol.AppsInstalledResponse, error) {
	var result protocol.AppsInstalledResponse
	if err := c.Call(ctx, "app/installed", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AppList(ctx context.Context, params protocol.AppsListParams) (*protocol.AppsListResponse, error) {
	var result protocol.AppsListResponse
	if err := c.Call(ctx, "app/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) AppRead(ctx context.Context, params protocol.AppsReadParams) (*protocol.AppsReadResponse, error) {
	var result protocol.AppsReadResponse
	if err := c.Call(ctx, "app/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExec(ctx context.Context, params protocol.CommandExecParams) (*protocol.CommandExecResponse, error) {
	var result protocol.CommandExecResponse
	if err := c.Call(ctx, "command/exec", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExecResize(ctx context.Context, params protocol.CommandExecResizeParams) (*protocol.CommandExecResizeResponse, error) {
	var result protocol.CommandExecResizeResponse
	if err := c.Call(ctx, "command/exec/resize", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExecTerminate(ctx context.Context, params protocol.CommandExecTerminateParams) (*protocol.CommandExecTerminateResponse, error) {
	var result protocol.CommandExecTerminateResponse
	if err := c.Call(ctx, "command/exec/terminate", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) CommandExecWrite(ctx context.Context, params protocol.CommandExecWriteParams) (*protocol.CommandExecWriteResponse, error) {
	var result protocol.CommandExecWriteResponse
	if err := c.Call(ctx, "command/exec/write", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigBatchWrite(ctx context.Context, params protocol.ConfigBatchWriteParams) (*protocol.ConfigWriteResponse, error) {
	var result protocol.ConfigWriteResponse
	if err := c.Call(ctx, "config/batchWrite", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigMCPServerReload(ctx context.Context) (*protocol.MCPServerRefreshResponse, error) {
	var result protocol.MCPServerRefreshResponse
	if err := c.Call(ctx, "config/mcpServer/reload", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ConfigMcpServerReload is the former spelling of ConfigMCPServerReload.
//
// Deprecated: use ConfigMCPServerReload.
func (c *Client) ConfigMcpServerReload(ctx context.Context) (*protocol.MCPServerRefreshResponse, error) {
	return c.ConfigMCPServerReload(ctx)
}

func (c *Client) ConfigRead(ctx context.Context, params protocol.ConfigReadParams) (*protocol.ConfigReadResponse, error) {
	var result protocol.ConfigReadResponse
	if err := c.Call(ctx, "config/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigValueWrite(ctx context.Context, params protocol.ConfigValueWriteParams) (*protocol.ConfigWriteResponse, error) {
	var result protocol.ConfigWriteResponse
	if err := c.Call(ctx, "config/value/write", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ConfigRequirementsRead(ctx context.Context) (*protocol.ConfigRequirementsReadResponse, error) {
	var result protocol.ConfigRequirementsReadResponse
	if err := c.Call(ctx, "configRequirements/read", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExperimentalFeatureEnablementSet(ctx context.Context, params protocol.ExperimentalFeatureEnablementSetParams) (*protocol.ExperimentalFeatureEnablementSetResponse, error) {
	var result protocol.ExperimentalFeatureEnablementSetResponse
	if err := c.Call(ctx, "experimentalFeature/enablement/set", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExperimentalFeatureList(ctx context.Context, params protocol.ExperimentalFeatureListParams) (*protocol.ExperimentalFeatureListResponse, error) {
	var result protocol.ExperimentalFeatureListResponse
	if err := c.Call(ctx, "experimentalFeature/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExternalAgentConfigDetect(ctx context.Context, params protocol.ExternalAgentConfigDetectParams) (*protocol.ExternalAgentConfigDetectResponse, error) {
	var result protocol.ExternalAgentConfigDetectResponse
	if err := c.Call(ctx, "externalAgentConfig/detect", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExternalAgentConfigImport(ctx context.Context, params protocol.ExternalAgentConfigImportParams) (*protocol.ExternalAgentConfigImportResponse, error) {
	var result protocol.ExternalAgentConfigImportResponse
	if err := c.Call(ctx, "externalAgentConfig/import", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExternalAgentConfigImportReadHistories(ctx context.Context) (*protocol.ExternalAgentConfigImportHistoriesReadResponse, error) {
	var result protocol.ExternalAgentConfigImportHistoriesReadResponse
	if err := c.Call(ctx, "externalAgentConfig/import/readHistories", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ExternalAgentConfigImportRecordHistory(ctx context.Context, params protocol.ExternalAgentConfigImportHistoryRecordParams) (*protocol.ExternalAgentConfigImportHistoryRecordResponse, error) {
	var result protocol.ExternalAgentConfigImportHistoryRecordResponse
	if err := c.Call(ctx, "externalAgentConfig/import/recordHistory", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FeedbackUpload(ctx context.Context, params protocol.FeedbackUploadParams) (*protocol.FeedbackUploadResponse, error) {
	var result protocol.FeedbackUploadResponse
	if err := c.Call(ctx, "feedback/upload", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsCopy(ctx context.Context, params protocol.FsCopyParams) (*protocol.FsCopyResponse, error) {
	var result protocol.FsCopyResponse
	if err := c.Call(ctx, "fs/copy", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsCreateDirectory(ctx context.Context, params protocol.FsCreateDirectoryParams) (*protocol.FsCreateDirectoryResponse, error) {
	var result protocol.FsCreateDirectoryResponse
	if err := c.Call(ctx, "fs/createDirectory", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsGetMetadata(ctx context.Context, params protocol.FsGetMetadataParams) (*protocol.FsGetMetadataResponse, error) {
	var result protocol.FsGetMetadataResponse
	if err := c.Call(ctx, "fs/getMetadata", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsReadDirectory(ctx context.Context, params protocol.FsReadDirectoryParams) (*protocol.FsReadDirectoryResponse, error) {
	var result protocol.FsReadDirectoryResponse
	if err := c.Call(ctx, "fs/readDirectory", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsReadFile(ctx context.Context, params protocol.FsReadFileParams) (*protocol.FsReadFileResponse, error) {
	var result protocol.FsReadFileResponse
	if err := c.Call(ctx, "fs/readFile", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsRemove(ctx context.Context, params protocol.FsRemoveParams) (*protocol.FsRemoveResponse, error) {
	var result protocol.FsRemoveResponse
	if err := c.Call(ctx, "fs/remove", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsUnwatch(ctx context.Context, params protocol.FsUnwatchParams) (*protocol.FsUnwatchResponse, error) {
	var result protocol.FsUnwatchResponse
	if err := c.Call(ctx, "fs/unwatch", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsWatch(ctx context.Context, params protocol.FsWatchParams) (*protocol.FsWatchResponse, error) {
	var result protocol.FsWatchResponse
	if err := c.Call(ctx, "fs/watch", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FsWriteFile(ctx context.Context, params protocol.FsWriteFileParams) (*protocol.FsWriteFileResponse, error) {
	var result protocol.FsWriteFileResponse
	if err := c.Call(ctx, "fs/writeFile", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) FuzzyFileSearch(ctx context.Context, params protocol.FuzzyFileSearchParams) (*protocol.FuzzyFileSearchResponse, error) {
	var result protocol.FuzzyFileSearchResponse
	if err := c.Call(ctx, "fuzzyFileSearch", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) HooksList(ctx context.Context, params protocol.HooksListParams) (*protocol.HooksListResponse, error) {
	var result protocol.HooksListResponse
	if err := c.Call(ctx, "hooks/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) Initialize(ctx context.Context, params protocol.InitializeParams) (*protocol.InitializeResponse, error) {
	var result protocol.InitializeResponse
	if err := c.Call(ctx, "initialize", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) MarketplaceAdd(ctx context.Context, params protocol.MarketplaceAddParams) (*protocol.MarketplaceAddResponse, error) {
	var result protocol.MarketplaceAddResponse
	if err := c.Call(ctx, "marketplace/add", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) MarketplaceRemove(ctx context.Context, params protocol.MarketplaceRemoveParams) (*protocol.MarketplaceRemoveResponse, error) {
	var result protocol.MarketplaceRemoveResponse
	if err := c.Call(ctx, "marketplace/remove", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) MarketplaceUpgrade(ctx context.Context, params protocol.MarketplaceUpgradeParams) (*protocol.MarketplaceUpgradeResponse, error) {
	var result protocol.MarketplaceUpgradeResponse
	if err := c.Call(ctx, "marketplace/upgrade", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) MCPServerOAuthLogin(ctx context.Context, params protocol.MCPServerOAuthLoginParams) (*protocol.MCPServerOAuthLoginResponse, error) {
	var result protocol.MCPServerOAuthLoginResponse
	if err := c.Call(ctx, "mcpServer/oauth/login", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// McpServerOauthLogin is the former spelling of MCPServerOAuthLogin.
//
// Deprecated: use MCPServerOAuthLogin.
func (c *Client) McpServerOauthLogin(ctx context.Context, params protocol.MCPServerOAuthLoginParams) (*protocol.MCPServerOAuthLoginResponse, error) {
	return c.MCPServerOAuthLogin(ctx, params)
}

func (c *Client) MCPServerResourceRead(ctx context.Context, params protocol.MCPResourceReadParams) (*protocol.MCPResourceReadResponse, error) {
	var result protocol.MCPResourceReadResponse
	if err := c.Call(ctx, "mcpServer/resource/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// McpServerResourceRead is the former spelling of MCPServerResourceRead.
//
// Deprecated: use MCPServerResourceRead.
func (c *Client) McpServerResourceRead(ctx context.Context, params protocol.MCPResourceReadParams) (*protocol.MCPResourceReadResponse, error) {
	return c.MCPServerResourceRead(ctx, params)
}

func (c *Client) MCPServerToolCall(ctx context.Context, params protocol.MCPServerToolCallParams) (*protocol.MCPServerToolCallResponse, error) {
	var result protocol.MCPServerToolCallResponse
	if err := c.Call(ctx, "mcpServer/tool/call", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// McpServerToolCall is the former spelling of MCPServerToolCall.
//
// Deprecated: use MCPServerToolCall.
func (c *Client) McpServerToolCall(ctx context.Context, params protocol.MCPServerToolCallParams) (*protocol.MCPServerToolCallResponse, error) {
	return c.MCPServerToolCall(ctx, params)
}

func (c *Client) MCPServerStatusList(ctx context.Context, params protocol.ListMCPServerStatusParams) (*protocol.ListMCPServerStatusResponse, error) {
	var result protocol.ListMCPServerStatusResponse
	if err := c.Call(ctx, "mcpServerStatus/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// McpServerStatusList is the former spelling of MCPServerStatusList.
//
// Deprecated: use MCPServerStatusList.
func (c *Client) McpServerStatusList(ctx context.Context, params protocol.ListMCPServerStatusParams) (*protocol.ListMCPServerStatusResponse, error) {
	return c.MCPServerStatusList(ctx, params)
}

func (c *Client) ModelList(ctx context.Context, params protocol.ModelListParams) (*protocol.ModelListResponse, error) {
	var result protocol.ModelListResponse
	if err := c.Call(ctx, "model/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ModelProviderCapabilitiesRead(ctx context.Context, params protocol.ModelProviderCapabilitiesReadParams) (*protocol.ModelProviderCapabilitiesReadResponse, error) {
	var result protocol.ModelProviderCapabilitiesReadResponse
	if err := c.Call(ctx, "modelProvider/capabilities/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PermissionProfileList(ctx context.Context, params protocol.PermissionProfileListParams) (*protocol.PermissionProfileListResponse, error) {
	var result protocol.PermissionProfileListResponse
	if err := c.Call(ctx, "permissionProfile/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginInstall(ctx context.Context, params protocol.PluginInstallParams) (*protocol.PluginInstallResponse, error) {
	var result protocol.PluginInstallResponse
	if err := c.Call(ctx, "plugin/install", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginInstalled(ctx context.Context, params protocol.PluginInstalledParams) (*protocol.PluginInstalledResponse, error) {
	var result protocol.PluginInstalledResponse
	if err := c.Call(ctx, "plugin/installed", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginList(ctx context.Context, params protocol.PluginListParams) (*protocol.PluginListResponse, error) {
	var result protocol.PluginListResponse
	if err := c.Call(ctx, "plugin/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginRead(ctx context.Context, params protocol.PluginReadParams) (*protocol.PluginReadResponse, error) {
	var result protocol.PluginReadResponse
	if err := c.Call(ctx, "plugin/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareCheckout(ctx context.Context, params protocol.PluginShareCheckoutParams) (*protocol.PluginShareCheckoutResponse, error) {
	var result protocol.PluginShareCheckoutResponse
	if err := c.Call(ctx, "plugin/share/checkout", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareDelete(ctx context.Context, params protocol.PluginShareDeleteParams) (*protocol.PluginShareDeleteResponse, error) {
	var result protocol.PluginShareDeleteResponse
	if err := c.Call(ctx, "plugin/share/delete", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareList(ctx context.Context, params protocol.PluginShareListParams) (*protocol.PluginShareListResponse, error) {
	var result protocol.PluginShareListResponse
	if err := c.Call(ctx, "plugin/share/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareSave(ctx context.Context, params protocol.PluginShareSaveParams) (*protocol.PluginShareSaveResponse, error) {
	var result protocol.PluginShareSaveResponse
	if err := c.Call(ctx, "plugin/share/save", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginShareUpdateTargets(ctx context.Context, params protocol.PluginShareUpdateTargetsParams) (*protocol.PluginShareUpdateTargetsResponse, error) {
	var result protocol.PluginShareUpdateTargetsResponse
	if err := c.Call(ctx, "plugin/share/updateTargets", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginSkillRead(ctx context.Context, params protocol.PluginSkillReadParams) (*protocol.PluginSkillReadResponse, error) {
	var result protocol.PluginSkillReadResponse
	if err := c.Call(ctx, "plugin/skill/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PluginUninstall(ctx context.Context, params protocol.PluginUninstallParams) (*protocol.PluginUninstallResponse, error) {
	var result protocol.PluginUninstallResponse
	if err := c.Call(ctx, "plugin/uninstall", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ReviewStart(ctx context.Context, params protocol.ReviewStartParams) (*protocol.ReviewStartResponse, error) {
	var result protocol.ReviewStartResponse
	if err := c.Call(ctx, "review/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SkillsConfigWrite(ctx context.Context, params protocol.SkillsConfigWriteParams) (*protocol.SkillsConfigWriteResponse, error) {
	var result protocol.SkillsConfigWriteResponse
	if err := c.Call(ctx, "skills/config/write", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SkillsExtraRootsSet(ctx context.Context, params protocol.SkillsExtraRootsSetParams) (*protocol.SkillsExtraRootsSetResponse, error) {
	var result protocol.SkillsExtraRootsSetResponse
	if err := c.Call(ctx, "skills/extraRoots/set", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) SkillsList(ctx context.Context, params protocol.SkillsListParams) (*protocol.SkillsListResponse, error) {
	var result protocol.SkillsListResponse
	if err := c.Call(ctx, "skills/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadApproveGuardianDeniedAction(ctx context.Context, params protocol.ThreadApproveGuardianDeniedActionParams) (*protocol.ThreadApproveGuardianDeniedActionResponse, error) {
	var result protocol.ThreadApproveGuardianDeniedActionResponse
	if err := c.Call(ctx, "thread/approveGuardianDeniedAction", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadArchive(ctx context.Context, params protocol.ThreadArchiveParams) (*protocol.ThreadArchiveResponse, error) {
	var result protocol.ThreadArchiveResponse
	if err := c.Call(ctx, "thread/archive", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadCompactStart(ctx context.Context, params protocol.ThreadCompactStartParams) (*protocol.ThreadCompactStartResponse, error) {
	var result protocol.ThreadCompactStartResponse
	if err := c.Call(ctx, "thread/compact/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadDelete(ctx context.Context, params protocol.ThreadDeleteParams) (*protocol.ThreadDeleteResponse, error) {
	var result protocol.ThreadDeleteResponse
	if err := c.Call(ctx, "thread/delete", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadFork(ctx context.Context, params protocol.ThreadForkParams) (*protocol.ThreadForkResponse, error) {
	var result protocol.ThreadForkResponse
	if err := c.Call(ctx, "thread/fork", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadGoalClear(ctx context.Context, params protocol.ThreadGoalClearParams) (*protocol.ThreadGoalClearResponse, error) {
	var result protocol.ThreadGoalClearResponse
	if err := c.Call(ctx, "thread/goal/clear", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadGoalGet(ctx context.Context, params protocol.ThreadGoalGetParams) (*protocol.ThreadGoalGetResponse, error) {
	var result protocol.ThreadGoalGetResponse
	if err := c.Call(ctx, "thread/goal/get", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadGoalSet(ctx context.Context, params protocol.ThreadGoalSetParams) (*protocol.ThreadGoalSetResponse, error) {
	var result protocol.ThreadGoalSetResponse
	if err := c.Call(ctx, "thread/goal/set", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadInjectItems(ctx context.Context, params protocol.ThreadInjectItemsParams) (*protocol.ThreadInjectItemsResponse, error) {
	var result protocol.ThreadInjectItemsResponse
	if err := c.Call(ctx, "thread/inject_items", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadList(ctx context.Context, params protocol.ThreadListParams) (*protocol.ThreadListResponse, error) {
	var result protocol.ThreadListResponse
	if err := c.Call(ctx, "thread/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadLoadedList(ctx context.Context, params protocol.ThreadLoadedListParams) (*protocol.ThreadLoadedListResponse, error) {
	var result protocol.ThreadLoadedListResponse
	if err := c.Call(ctx, "thread/loaded/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadMetadataUpdate(ctx context.Context, params protocol.ThreadMetadataUpdateParams) (*protocol.ThreadMetadataUpdateResponse, error) {
	var result protocol.ThreadMetadataUpdateResponse
	if err := c.Call(ctx, "thread/metadata/update", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadNameSet(ctx context.Context, params protocol.ThreadSetNameParams) (*protocol.ThreadSetNameResponse, error) {
	var result protocol.ThreadSetNameResponse
	if err := c.Call(ctx, "thread/name/set", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadRead(ctx context.Context, params protocol.ThreadReadParams) (*protocol.ThreadReadResponse, error) {
	var result protocol.ThreadReadResponse
	if err := c.Call(ctx, "thread/read", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadResume(ctx context.Context, params protocol.ThreadResumeParams) (*protocol.ThreadResumeResponse, error) {
	var result protocol.ThreadResumeResponse
	if err := c.Call(ctx, "thread/resume", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadRollback(ctx context.Context, params protocol.ThreadRollbackParams) (*protocol.ThreadRollbackResponse, error) {
	var result protocol.ThreadRollbackResponse
	if err := c.Call(ctx, "thread/rollback", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadSectionMove(ctx context.Context, params protocol.ThreadSectionMoveParams) (*protocol.ThreadSectionMoveResponse, error) {
	var result protocol.ThreadSectionMoveResponse
	if err := c.Call(ctx, "thread/section/move", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadShellCommand(ctx context.Context, params protocol.ThreadShellCommandParams) (*protocol.ThreadShellCommandResponse, error) {
	var result protocol.ThreadShellCommandResponse
	if err := c.Call(ctx, "thread/shellCommand", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadStart(ctx context.Context, params protocol.ThreadStartParams) (*protocol.ThreadStartResponse, error) {
	var result protocol.ThreadStartResponse
	if err := c.Call(ctx, "thread/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadUnarchive(ctx context.Context, params protocol.ThreadUnarchiveParams) (*protocol.ThreadUnarchiveResponse, error) {
	var result protocol.ThreadUnarchiveResponse
	if err := c.Call(ctx, "thread/unarchive", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadUnsubscribe(ctx context.Context, params protocol.ThreadUnsubscribeParams) (*protocol.ThreadUnsubscribeResponse, error) {
	var result protocol.ThreadUnsubscribeResponse
	if err := c.Call(ctx, "thread/unsubscribe", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadSectionCreate(ctx context.Context, params protocol.ThreadSectionCreateParams) (*protocol.ThreadSectionCreateResponse, error) {
	var result protocol.ThreadSectionCreateResponse
	if err := c.Call(ctx, "threadSection/create", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadSectionDelete(ctx context.Context, params protocol.ThreadSectionDeleteParams) (*protocol.ThreadSectionDeleteResponse, error) {
	var result protocol.ThreadSectionDeleteResponse
	if err := c.Call(ctx, "threadSection/delete", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadSectionList(ctx context.Context, params protocol.ThreadSectionListParams) (*protocol.ThreadSectionListResponse, error) {
	var result protocol.ThreadSectionListResponse
	if err := c.Call(ctx, "threadSection/list", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) ThreadSectionUpdate(ctx context.Context, params protocol.ThreadSectionUpdateParams) (*protocol.ThreadSectionUpdateResponse, error) {
	var result protocol.ThreadSectionUpdateResponse
	if err := c.Call(ctx, "threadSection/update", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) TurnInterrupt(ctx context.Context, params protocol.TurnInterruptParams) (*protocol.TurnInterruptResponse, error) {
	var result protocol.TurnInterruptResponse
	if err := c.Call(ctx, "turn/interrupt", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) TurnStart(ctx context.Context, params protocol.TurnStartParams) (*protocol.TurnStartResponse, error) {
	var result protocol.TurnStartResponse
	if err := c.Call(ctx, "turn/start", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) TurnSteer(ctx context.Context, params protocol.TurnSteerParams) (*protocol.TurnSteerResponse, error) {
	var result protocol.TurnSteerResponse
	if err := c.Call(ctx, "turn/steer", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) WindowsSandboxReadiness(ctx context.Context) (*protocol.WindowsSandboxReadinessResponse, error) {
	var result protocol.WindowsSandboxReadinessResponse
	if err := c.Call(ctx, "windowsSandbox/readiness", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) WindowsSandboxSetupStart(ctx context.Context, params protocol.WindowsSandboxSetupStartParams) (*protocol.WindowsSandboxSetupStartResponse, error) {
	var result protocol.WindowsSandboxSetupStartResponse
	if err := c.Call(ctx, "windowsSandbox/setupStart", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BuildClientRequest builds a JSON-RPC request for a client method.
func BuildClientRequest(method string, params any, id RequestID) (JSONRPCRequest, error) {
	var raw json.RawMessage
	if params != nil {
		data, err := json.Marshal(params)
		if err != nil {
			return JSONRPCRequest{}, err
		}
		raw = data
	}
	return JSONRPCRequest{ID: id, Method: method, Params: raw}, nil
}
