// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 3fe0e022be909a27126dd722769a5f697bb14d59

package rpc

import (
	"encoding/json"

	"github.com/pmenglund/codex-sdk-go/protocol"
)

// Notification represents a typed server notification.
type Notification struct {
	Method string
	Params any
	Raw json.RawMessage
}

type notificationParser func(json.RawMessage) (Notification, error)

var notificationParsers = map[string]notificationParser{
	"account/login/completed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.AccountLoginCompletedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "account/login/completed", Raw: params}, err
			}
		}
		return Notification{Method: "account/login/completed", Params: payload, Raw: params}, nil
	},
	"account/rateLimits/updated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.AccountRateLimitsUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "account/rateLimits/updated", Raw: params}, err
			}
		}
		return Notification{Method: "account/rateLimits/updated", Params: payload, Raw: params}, nil
	},
	"account/updated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.AccountUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "account/updated", Raw: params}, err
			}
		}
		return Notification{Method: "account/updated", Params: payload, Raw: params}, nil
	},
	"app/list/updated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.AppListUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "app/list/updated", Raw: params}, err
			}
		}
		return Notification{Method: "app/list/updated", Params: payload, Raw: params}, nil
	},
	"command/exec/outputDelta": func(params json.RawMessage) (Notification, error) {
		var payload protocol.CommandExecOutputDeltaNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "command/exec/outputDelta", Raw: params}, err
			}
		}
		return Notification{Method: "command/exec/outputDelta", Params: payload, Raw: params}, nil
	},
	"configWarning": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ConfigWarningNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "configWarning", Raw: params}, err
			}
		}
		return Notification{Method: "configWarning", Params: payload, Raw: params}, nil
	},
	"deprecationNotice": func(params json.RawMessage) (Notification, error) {
		var payload protocol.DeprecationNoticeNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "deprecationNotice", Raw: params}, err
			}
		}
		return Notification{Method: "deprecationNotice", Params: payload, Raw: params}, nil
	},
	"error": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ErrorNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "error", Raw: params}, err
			}
		}
		return Notification{Method: "error", Params: payload, Raw: params}, nil
	},
	"fs/changed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.FsChangedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "fs/changed", Raw: params}, err
			}
		}
		return Notification{Method: "fs/changed", Params: payload, Raw: params}, nil
	},
	"fuzzyFileSearch/sessionCompleted": func(params json.RawMessage) (Notification, error) {
		var payload protocol.FuzzyFileSearchSessionCompletedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "fuzzyFileSearch/sessionCompleted", Raw: params}, err
			}
		}
		return Notification{Method: "fuzzyFileSearch/sessionCompleted", Params: payload, Raw: params}, nil
	},
	"fuzzyFileSearch/sessionUpdated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.FuzzyFileSearchSessionUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "fuzzyFileSearch/sessionUpdated", Raw: params}, err
			}
		}
		return Notification{Method: "fuzzyFileSearch/sessionUpdated", Params: payload, Raw: params}, nil
	},
	"hook/completed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.HookCompletedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "hook/completed", Raw: params}, err
			}
		}
		return Notification{Method: "hook/completed", Params: payload, Raw: params}, nil
	},
	"hook/started": func(params json.RawMessage) (Notification, error) {
		var payload protocol.HookStartedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "hook/started", Raw: params}, err
			}
		}
		return Notification{Method: "hook/started", Params: payload, Raw: params}, nil
	},
	"item/agentMessage/delta": func(params json.RawMessage) (Notification, error) {
		var payload protocol.AgentMessageDeltaNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/agentMessage/delta", Raw: params}, err
			}
		}
		return Notification{Method: "item/agentMessage/delta", Params: payload, Raw: params}, nil
	},
	"item/autoApprovalReview/completed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ItemGuardianApprovalReviewCompletedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/autoApprovalReview/completed", Raw: params}, err
			}
		}
		return Notification{Method: "item/autoApprovalReview/completed", Params: payload, Raw: params}, nil
	},
	"item/autoApprovalReview/started": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ItemGuardianApprovalReviewStartedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/autoApprovalReview/started", Raw: params}, err
			}
		}
		return Notification{Method: "item/autoApprovalReview/started", Params: payload, Raw: params}, nil
	},
	"item/commandExecution/outputDelta": func(params json.RawMessage) (Notification, error) {
		var payload protocol.CommandExecutionOutputDeltaNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/commandExecution/outputDelta", Raw: params}, err
			}
		}
		return Notification{Method: "item/commandExecution/outputDelta", Params: payload, Raw: params}, nil
	},
	"item/commandExecution/terminalInteraction": func(params json.RawMessage) (Notification, error) {
		var payload protocol.TerminalInteractionNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/commandExecution/terminalInteraction", Raw: params}, err
			}
		}
		return Notification{Method: "item/commandExecution/terminalInteraction", Params: payload, Raw: params}, nil
	},
	"item/completed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ItemCompletedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/completed", Raw: params}, err
			}
		}
		return Notification{Method: "item/completed", Params: payload, Raw: params}, nil
	},
	"item/fileChange/outputDelta": func(params json.RawMessage) (Notification, error) {
		var payload protocol.FileChangeOutputDeltaNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/fileChange/outputDelta", Raw: params}, err
			}
		}
		return Notification{Method: "item/fileChange/outputDelta", Params: payload, Raw: params}, nil
	},
	"item/mcpToolCall/progress": func(params json.RawMessage) (Notification, error) {
		var payload protocol.McpToolCallProgressNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/mcpToolCall/progress", Raw: params}, err
			}
		}
		return Notification{Method: "item/mcpToolCall/progress", Params: payload, Raw: params}, nil
	},
	"item/plan/delta": func(params json.RawMessage) (Notification, error) {
		var payload protocol.PlanDeltaNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/plan/delta", Raw: params}, err
			}
		}
		return Notification{Method: "item/plan/delta", Params: payload, Raw: params}, nil
	},
	"item/reasoning/summaryPartAdded": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ReasoningSummaryPartAddedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/reasoning/summaryPartAdded", Raw: params}, err
			}
		}
		return Notification{Method: "item/reasoning/summaryPartAdded", Params: payload, Raw: params}, nil
	},
	"item/reasoning/summaryTextDelta": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ReasoningSummaryTextDeltaNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/reasoning/summaryTextDelta", Raw: params}, err
			}
		}
		return Notification{Method: "item/reasoning/summaryTextDelta", Params: payload, Raw: params}, nil
	},
	"item/reasoning/textDelta": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ReasoningTextDeltaNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/reasoning/textDelta", Raw: params}, err
			}
		}
		return Notification{Method: "item/reasoning/textDelta", Params: payload, Raw: params}, nil
	},
	"item/started": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ItemStartedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "item/started", Raw: params}, err
			}
		}
		return Notification{Method: "item/started", Params: payload, Raw: params}, nil
	},
	"mcpServer/oauthLogin/completed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.McpServerOauthLoginCompletedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "mcpServer/oauthLogin/completed", Raw: params}, err
			}
		}
		return Notification{Method: "mcpServer/oauthLogin/completed", Params: payload, Raw: params}, nil
	},
	"mcpServer/startupStatus/updated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.McpServerStatusUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "mcpServer/startupStatus/updated", Raw: params}, err
			}
		}
		return Notification{Method: "mcpServer/startupStatus/updated", Params: payload, Raw: params}, nil
	},
	"model/rerouted": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ModelReroutedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "model/rerouted", Raw: params}, err
			}
		}
		return Notification{Method: "model/rerouted", Params: payload, Raw: params}, nil
	},
	"serverRequest/resolved": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ServerRequestResolvedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "serverRequest/resolved", Raw: params}, err
			}
		}
		return Notification{Method: "serverRequest/resolved", Params: payload, Raw: params}, nil
	},
	"skills/changed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.SkillsChangedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "skills/changed", Raw: params}, err
			}
		}
		return Notification{Method: "skills/changed", Params: payload, Raw: params}, nil
	},
	"thread/archived": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadArchivedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/archived", Raw: params}, err
			}
		}
		return Notification{Method: "thread/archived", Params: payload, Raw: params}, nil
	},
	"thread/closed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadClosedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/closed", Raw: params}, err
			}
		}
		return Notification{Method: "thread/closed", Params: payload, Raw: params}, nil
	},
	"thread/compacted": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ContextCompactedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/compacted", Raw: params}, err
			}
		}
		return Notification{Method: "thread/compacted", Params: payload, Raw: params}, nil
	},
	"thread/name/updated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadNameUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/name/updated", Raw: params}, err
			}
		}
		return Notification{Method: "thread/name/updated", Params: payload, Raw: params}, nil
	},
	"thread/realtime/closed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadRealtimeClosedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/realtime/closed", Raw: params}, err
			}
		}
		return Notification{Method: "thread/realtime/closed", Params: payload, Raw: params}, nil
	},
	"thread/realtime/error": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadRealtimeErrorNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/realtime/error", Raw: params}, err
			}
		}
		return Notification{Method: "thread/realtime/error", Params: payload, Raw: params}, nil
	},
	"thread/realtime/itemAdded": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadRealtimeItemAddedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/realtime/itemAdded", Raw: params}, err
			}
		}
		return Notification{Method: "thread/realtime/itemAdded", Params: payload, Raw: params}, nil
	},
	"thread/realtime/outputAudio/delta": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadRealtimeOutputAudioDeltaNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/realtime/outputAudio/delta", Raw: params}, err
			}
		}
		return Notification{Method: "thread/realtime/outputAudio/delta", Params: payload, Raw: params}, nil
	},
	"thread/realtime/sdp": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadRealtimeSdpNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/realtime/sdp", Raw: params}, err
			}
		}
		return Notification{Method: "thread/realtime/sdp", Params: payload, Raw: params}, nil
	},
	"thread/realtime/started": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadRealtimeStartedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/realtime/started", Raw: params}, err
			}
		}
		return Notification{Method: "thread/realtime/started", Params: payload, Raw: params}, nil
	},
	"thread/realtime/transcriptUpdated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadRealtimeTranscriptUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/realtime/transcriptUpdated", Raw: params}, err
			}
		}
		return Notification{Method: "thread/realtime/transcriptUpdated", Params: payload, Raw: params}, nil
	},
	"thread/started": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadStartedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/started", Raw: params}, err
			}
		}
		return Notification{Method: "thread/started", Params: payload, Raw: params}, nil
	},
	"thread/status/changed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadStatusChangedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/status/changed", Raw: params}, err
			}
		}
		return Notification{Method: "thread/status/changed", Params: payload, Raw: params}, nil
	},
	"thread/tokenUsage/updated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadTokenUsageUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/tokenUsage/updated", Raw: params}, err
			}
		}
		return Notification{Method: "thread/tokenUsage/updated", Params: payload, Raw: params}, nil
	},
	"thread/unarchived": func(params json.RawMessage) (Notification, error) {
		var payload protocol.ThreadUnarchivedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "thread/unarchived", Raw: params}, err
			}
		}
		return Notification{Method: "thread/unarchived", Params: payload, Raw: params}, nil
	},
	"turn/completed": func(params json.RawMessage) (Notification, error) {
		var payload protocol.TurnCompletedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "turn/completed", Raw: params}, err
			}
		}
		return Notification{Method: "turn/completed", Params: payload, Raw: params}, nil
	},
	"turn/diff/updated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.TurnDiffUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "turn/diff/updated", Raw: params}, err
			}
		}
		return Notification{Method: "turn/diff/updated", Params: payload, Raw: params}, nil
	},
	"turn/plan/updated": func(params json.RawMessage) (Notification, error) {
		var payload protocol.TurnPlanUpdatedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "turn/plan/updated", Raw: params}, err
			}
		}
		return Notification{Method: "turn/plan/updated", Params: payload, Raw: params}, nil
	},
	"turn/started": func(params json.RawMessage) (Notification, error) {
		var payload protocol.TurnStartedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "turn/started", Raw: params}, err
			}
		}
		return Notification{Method: "turn/started", Params: payload, Raw: params}, nil
	},
	"windows/worldWritableWarning": func(params json.RawMessage) (Notification, error) {
		var payload protocol.WindowsWorldWritableWarningNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "windows/worldWritableWarning", Raw: params}, err
			}
		}
		return Notification{Method: "windows/worldWritableWarning", Params: payload, Raw: params}, nil
	},
	"windowsSandbox/setupCompleted": func(params json.RawMessage) (Notification, error) {
		var payload protocol.WindowsSandboxSetupCompletedNotification
		if len(params) > 0 {
			if err := json.Unmarshal(params, &payload); err != nil {
				return Notification{Method: "windowsSandbox/setupCompleted", Raw: params}, err
			}
		}
		return Notification{Method: "windowsSandbox/setupCompleted", Params: payload, Raw: params}, nil
	},
}

func parseServerNotification(method string, params json.RawMessage) (Notification, error) {
	if handler, ok := notificationParsers[method]; ok {
		return handler(params)
	}
	return Notification{Method: method, Raw: params}, nil
}
