// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 25af12f7e61572b0bc18ddb1008be543b91519b0

package rpc

import (
	"context"
	"encoding/json"

	"github.com/pmenglund/codex-sdk-go/protocol"
)

// MCPServerElicitationRequestHandler handles mcpServer/elicitation/request using canonical Go initialisms.
type MCPServerElicitationRequestHandler interface {
	MCPServerElicitationRequest(ctx context.Context, params protocol.MCPServerElicitationRequestParams) (*protocol.MCPServerElicitationRequestResponse, error)
}

// ServerRequestHandler handles requests initiated by the app-server. Embed
// UnimplementedServerRequestHandler so newly added methods do not break implementations.
// Canonical-initialism capability interfaces take precedence over legacy method spellings.
//
// Deprecated: embed UnimplementedServerRequestHandler and override only required methods.
type ServerRequestHandler interface {
	AccountChatgptAuthTokensRefresh(ctx context.Context, params protocol.ChatgptAuthTokensRefreshParams) (*protocol.ChatgptAuthTokensRefreshResponse, error)
	ApplyPatchApproval(ctx context.Context, params protocol.ApplyPatchApprovalParams) (*protocol.ApplyPatchApprovalResponse, error)
	AttestationGenerate(ctx context.Context, params protocol.AttestationGenerateParams) (*protocol.AttestationGenerateResponse, error)
	ExecCommandApproval(ctx context.Context, params protocol.ExecCommandApprovalParams) (*protocol.ExecCommandApprovalResponse, error)
	ItemCommandExecutionRequestApproval(ctx context.Context, params protocol.CommandExecutionRequestApprovalParams) (*protocol.CommandExecutionRequestApprovalResponse, error)
	ItemFileChangeRequestApproval(ctx context.Context, params protocol.FileChangeRequestApprovalParams) (*protocol.FileChangeRequestApprovalResponse, error)
	ItemPermissionsRequestApproval(ctx context.Context, params protocol.PermissionsRequestApprovalParams) (*protocol.PermissionsRequestApprovalResponse, error)
	ItemToolCall(ctx context.Context, params protocol.DynamicToolCallParams) (*protocol.DynamicToolCallResponse, error)
	ItemToolRequestUserInput(ctx context.Context, params protocol.ToolRequestUserInputParams) (*protocol.ToolRequestUserInputResponse, error)
	McpServerElicitationRequest(ctx context.Context, params protocol.MCPServerElicitationRequestParams) (*protocol.MCPServerElicitationRequestResponse, error)
}

// UnimplementedServerRequestHandler provides forward-compatible default methods.
type UnimplementedServerRequestHandler struct{}

func (UnimplementedServerRequestHandler) AccountChatgptAuthTokensRefresh(context.Context, protocol.ChatgptAuthTokensRefreshParams) (*protocol.ChatgptAuthTokensRefreshResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) ApplyPatchApproval(context.Context, protocol.ApplyPatchApprovalParams) (*protocol.ApplyPatchApprovalResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) AttestationGenerate(context.Context, protocol.AttestationGenerateParams) (*protocol.AttestationGenerateResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) ExecCommandApproval(context.Context, protocol.ExecCommandApprovalParams) (*protocol.ExecCommandApprovalResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) ItemCommandExecutionRequestApproval(context.Context, protocol.CommandExecutionRequestApprovalParams) (*protocol.CommandExecutionRequestApprovalResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) ItemFileChangeRequestApproval(context.Context, protocol.FileChangeRequestApprovalParams) (*protocol.FileChangeRequestApprovalResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) ItemPermissionsRequestApproval(context.Context, protocol.PermissionsRequestApprovalParams) (*protocol.PermissionsRequestApprovalResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) ItemToolCall(context.Context, protocol.DynamicToolCallParams) (*protocol.DynamicToolCallResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) ItemToolRequestUserInput(context.Context, protocol.ToolRequestUserInputParams) (*protocol.ToolRequestUserInputResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func (UnimplementedServerRequestHandler) McpServerElicitationRequest(context.Context, protocol.MCPServerElicitationRequestParams) (*protocol.MCPServerElicitationRequestResponse, error) {
	return nil, ErrServerRequestUnsupported
}

func dispatchServerRequest(ctx context.Context, handler ServerRequestHandler, req JSONRPCRequest) (result any, err error) {
	switch req.Method {
	case "account/chatgptAuthTokens/refresh":
		var params protocol.ChatgptAuthTokensRefreshParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.AccountChatgptAuthTokensRefresh(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "applyPatchApproval":
		var params protocol.ApplyPatchApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.ApplyPatchApproval(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "attestation/generate":
		var params protocol.AttestationGenerateParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.AttestationGenerate(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "execCommandApproval":
		var params protocol.ExecCommandApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.ExecCommandApproval(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "item/commandExecution/requestApproval":
		var params protocol.CommandExecutionRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.ItemCommandExecutionRequestApproval(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "item/fileChange/requestApproval":
		var params protocol.FileChangeRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.ItemFileChangeRequestApproval(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "item/permissions/requestApproval":
		var params protocol.PermissionsRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.ItemPermissionsRequestApproval(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "item/tool/call":
		var params protocol.DynamicToolCallParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.ItemToolCall(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "item/tool/requestUserInput":
		var params protocol.ToolRequestUserInputParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		result, err = handler.ItemToolRequestUserInput(ctx, params)
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	case "mcpServer/elicitation/request":
		var params protocol.MCPServerElicitationRequestParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, &ServerRequestParamsError{Method: req.Method, Err: err}
			}
		}
		if canonicalHandler, ok := handler.(MCPServerElicitationRequestHandler); ok {
			result, err = canonicalHandler.MCPServerElicitationRequest(ctx, params)
		} else {
			result, err = handler.McpServerElicitationRequest(ctx, params)
		}
		if err != nil {
			return nil, &ServerRequestHandlerError{Method: req.Method, Err: err}
		}
		return result, nil
	default:
		return nil, &ServerRequestMethodError{Method: req.Method}
	}
}
