// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 0fa45fbca4a33a4325bee1177c75f22c465e294e

package rpc

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/pmenglund/codex-sdk-go/protocol"
)

// ServerRequestHandler handles requests initiated by the app-server.
type ServerRequestHandler interface {
	ApplyPatchApproval(ctx context.Context, params protocol.ApplyPatchApprovalParams) (*protocol.ApplyPatchApprovalResponse, error)
	ExecCommandApproval(ctx context.Context, params protocol.ExecCommandApprovalParams) (*protocol.ExecCommandApprovalResponse, error)
	ItemCommandExecutionRequestApproval(ctx context.Context, params protocol.CommandExecutionRequestApprovalParams) (*protocol.CommandExecutionRequestApprovalResponse, error)
	ItemFileChangeRequestApproval(ctx context.Context, params protocol.FileChangeRequestApprovalParams) (*protocol.FileChangeRequestApprovalResponse, error)
	ItemToolRequestUserInput(ctx context.Context, params protocol.ToolRequestUserInputParams) (*protocol.ToolRequestUserInputResponse, error)
}

func dispatchServerRequest(ctx context.Context, handler ServerRequestHandler, req JSONRPCRequest) (any, error) {
	switch req.Method {
	case "applyPatchApproval":
		var params protocol.ApplyPatchApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ApplyPatchApproval(ctx, params)
	case "execCommandApproval":
		var params protocol.ExecCommandApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ExecCommandApproval(ctx, params)
	case "item/commandExecution/requestApproval":
		var params protocol.CommandExecutionRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemCommandExecutionRequestApproval(ctx, params)
	case "item/fileChange/requestApproval":
		var params protocol.FileChangeRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemFileChangeRequestApproval(ctx, params)
	case "item/tool/requestUserInput":
		var params protocol.ToolRequestUserInputParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemToolRequestUserInput(ctx, params)
	default:
		return nil, fmt.Errorf("unsupported server request %q", req.Method)
	}
}
