// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 65319eb1400cbd2890c43d572263dabd25f18ba9

package rpc

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/pmenglund/codex-sdk-go/protocol"
)

// ServerRequestHandler handles requests initiated by the app-server.
type ServerRequestHandler interface {
	AccountChatgptAuthTokensRefresh(ctx context.Context, params protocol.ChatgptAuthTokensRefreshParams) (*protocol.ChatgptAuthTokensRefreshResponse, error)
	ApplyPatchApproval(ctx context.Context, params protocol.ApplyPatchApprovalParams) (*protocol.ApplyPatchApprovalResponse, error)
	ExecCommandApproval(ctx context.Context, params protocol.ExecCommandApprovalParams) (*protocol.ExecCommandApprovalResponse, error)
	ItemCommandExecutionRequestApproval(ctx context.Context, params protocol.CommandExecutionRequestApprovalParams) (*protocol.CommandExecutionRequestApprovalResponse, error)
	ItemFileChangeRequestApproval(ctx context.Context, params protocol.FileChangeRequestApprovalParams) (*protocol.FileChangeRequestApprovalResponse, error)
	ItemPermissionsRequestApproval(ctx context.Context, params protocol.PermissionsRequestApprovalParams) (*protocol.PermissionsRequestApprovalResponse, error)
	ItemToolCall(ctx context.Context, params protocol.DynamicToolCallParams) (*protocol.DynamicToolCallResponse, error)
	ItemToolRequestUserInput(ctx context.Context, params protocol.ToolRequestUserInputParams) (*protocol.ToolRequestUserInputResponse, error)
	McpServerElicitationRequest(ctx context.Context, params protocol.McpServerElicitationRequestParams) (*protocol.McpServerElicitationRequestResponse, error)
}

func dispatchServerRequest(ctx context.Context, handler ServerRequestHandler, req JSONRPCRequest) (any, error) {
	switch req.Method {
	case "account/chatgptAuthTokens/refresh":
		var params protocol.ChatgptAuthTokensRefreshParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.AccountChatgptAuthTokensRefresh(ctx, params)
	case "applyPatchApproval":
		var params protocol.ApplyPatchApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ApplyPatchApproval(ctx, params)
	case "execCommandApproval":
		var params protocol.ExecCommandApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ExecCommandApproval(ctx, params)
	case "item/commandExecution/requestApproval":
		var params protocol.CommandExecutionRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemCommandExecutionRequestApproval(ctx, params)
	case "item/fileChange/requestApproval":
		var params protocol.FileChangeRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemFileChangeRequestApproval(ctx, params)
	case "item/permissions/requestApproval":
		var params protocol.PermissionsRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemPermissionsRequestApproval(ctx, params)
	case "item/tool/call":
		var params protocol.DynamicToolCallParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemToolCall(ctx, params)
	case "item/tool/requestUserInput":
		var params protocol.ToolRequestUserInputParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemToolRequestUserInput(ctx, params)
	case "mcpServer/elicitation/request":
		var params protocol.McpServerElicitationRequestParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.McpServerElicitationRequest(ctx, params)
	default:
		return nil, fmt.Errorf("unsupported server request %q", req.Method)
	}
}
