package main

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/atombender/go-jsonschema/pkg/generator"
)

const testCodexCommit = "0123456789abcdef0123456789abcdef01234567"

func TestMethodBaseName(t *testing.T) {
	if got := methodBaseName("account/login/start"); got != "AccountLoginStart" {
		t.Fatalf("unexpected base name: %s", got)
	}
	if got := methodBaseName("turn/started"); got != "TurnStarted" {
		t.Fatalf("unexpected base name: %s", got)
	}
	if got := methodName(""); got != "Unknown" {
		t.Fatalf("expected Unknown, got %s", got)
	}
}

func TestNormalizeGeneratedHeader(t *testing.T) {
	src := []byte("// Code generated by some tool.\n\npackage foo\n")
	normalized := normalizeGeneratedHeader(src, testCodexCommit)
	if !strings.HasPrefix(string(normalized), generatedHeader(testCodexCommit)) {
		t.Fatalf("expected generated header prefix, got %q", string(normalized))
	}
	if !strings.Contains(string(normalized), "package foo") {
		t.Fatalf("expected package line to remain, got %q", string(normalized))
	}

	unchanged := []byte("package bar\n")
	if got := normalizeGeneratedHeader(unchanged, testCodexCommit); string(got) != string(unchanged) {
		t.Fatalf("expected header to remain unchanged, got %q", string(got))
	}
}

func TestRefName(t *testing.T) {
	if got := refName("#/definitions/Foo"); got != "Foo" {
		t.Fatalf("unexpected ref name: %s", got)
	}
	if got := refName("Bar"); got != "Bar" {
		t.Fatalf("unexpected ref name: %s", got)
	}
}

func TestResolveResponseType(t *testing.T) {
	defs := map[string]struct{}{
		"FooResponse": {},
		"BarResponse": {},
	}
	method := rpcMethod{Method: "foo", ParamsType: "FooParams"}
	resp, err := resolveResponseType(method, defs, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp != "FooResponse" {
		t.Fatalf("unexpected response type: %s", resp)
	}

	override := map[string]string{"foo": "OverrideResponse"}
	resp, err = resolveResponseType(method, defs, override)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp != "OverrideResponse" {
		t.Fatalf("unexpected override response type: %s", resp)
	}

	_, err = resolveResponseType(rpcMethod{Method: "missing"}, defs, nil)
	if err == nil {
		t.Fatalf("expected error for missing response type")
	}
}

func TestBuildRPCMethods(t *testing.T) {
	defs := map[string]struct{}{
		"FooResponse": {},
	}
	methods := []rpcMethod{{Method: "foo", ParamsType: "FooParams"}}
	out, err := buildRPCMethods(methods, defs, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if out[0].ResponseType != "FooResponse" {
		t.Fatalf("unexpected response type: %s", out[0].ResponseType)
	}
}

func TestLoadMethodsAndNotifications(t *testing.T) {
	dir := t.TempDir()
	methodPath := filepath.Join(dir, "ClientRequest.json")
	payload := oneOfSchema{
		OneOf: []schemaVariant{
			{Properties: map[string]schemaProperty{"method": {Enum: []string{"foo/bar"}}, "params": {Ref: "#/definitions/FooParams"}}},
			{Properties: map[string]schemaProperty{"method": {Enum: []string{"baz"}}, "params": {Type: "null"}}},
		},
	}
	writeJSON(t, methodPath, payload)

	methods, err := loadMethods(methodPath)
	if err != nil {
		t.Fatalf("loadMethods error: %v", err)
	}
	if len(methods) != 2 {
		t.Fatalf("expected 2 methods, got %d", len(methods))
	}
	if methods[0].Method != "baz" || methods[1].Method != "foo/bar" {
		t.Fatalf("unexpected methods: %#v", methods)
	}

	notifyPath := filepath.Join(dir, "ServerNotification.json")
	writeJSON(t, notifyPath, payload)
	notes, err := loadNotifications(notifyPath)
	if err != nil {
		t.Fatalf("loadNotifications error: %v", err)
	}
	if len(notes) != 2 || notes[0].Method != "baz" {
		t.Fatalf("unexpected notifications: %#v", notes)
	}
}

func TestStripAndSanitize(t *testing.T) {
	input := map[string]any{
		"oneOf": []any{map[string]any{"type": "string"}},
		"anyOf": []any{map[string]any{"type": "number"}},
		"nested": map[string]any{
			"oneOf": []any{map[string]any{"type": "object"}},
		},
	}
	stripSubschemas(input)
	if _, ok := input["oneOf"]; ok {
		t.Fatalf("expected oneOf removed")
	}
	if _, ok := input["anyOf"]; ok {
		t.Fatalf("expected anyOf removed")
	}
	nested := input["nested"].(map[string]any)
	if _, ok := nested["oneOf"]; ok {
		t.Fatalf("expected nested oneOf removed")
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "schema.json")
	writeJSON(t, path, input)

	sanitized, cleanup, err := sanitizeSchemaFile(path)
	if err != nil {
		t.Fatalf("sanitizeSchemaFile error: %v", err)
	}
	defer cleanup()

	data, err := os.ReadFile(sanitized)
	if err != nil {
		t.Fatalf("read sanitized file: %v", err)
	}
	if strings.Contains(string(data), "oneOf") || strings.Contains(string(data), "anyOf") {
		t.Fatalf("expected oneOf/anyOf stripped from sanitized file")
	}
}

func TestStripSubschemasHandlesArrays(t *testing.T) {
	input := []any{
		map[string]any{"oneOf": []any{map[string]any{"type": "string"}}},
		map[string]any{"nested": []any{map[string]any{"anyOf": []any{map[string]any{"type": "number"}}}}},
	}
	stripSubschemas(input)
	if _, ok := input[0].(map[string]any)["oneOf"]; ok {
		t.Fatalf("expected oneOf removed from array child")
	}
	nested := input[1].(map[string]any)["nested"].([]any)[0].(map[string]any)
	if _, ok := nested["anyOf"]; ok {
		t.Fatalf("expected anyOf removed from nested array child")
	}
}

func TestSanitizeSchemaFileErrors(t *testing.T) {
	if _, _, err := sanitizeSchemaFile(filepath.Join(t.TempDir(), "missing.json")); err == nil {
		t.Fatalf("expected missing file error")
	}

	path := filepath.Join(t.TempDir(), "bad.json")
	if err := os.WriteFile(path, []byte("{bad"), 0o644); err != nil {
		t.Fatalf("write bad schema: %v", err)
	}
	if _, _, err := sanitizeSchemaFile(path); err == nil {
		t.Fatalf("expected invalid json error")
	}
}

func TestCollectGeneratedTypes(t *testing.T) {
	sources := map[string][]byte{
		"a.go": []byte("package protocol\n\ntype Foo struct{}\n"),
		"b.go": []byte("package protocol\n\ntype Bar interface{}\n"),
	}
	generated := collectGeneratedTypes(sources)
	if _, ok := generated["Foo"]; !ok {
		t.Fatalf("expected Foo in generated types")
	}
	if _, ok := generated["Bar"]; !ok {
		t.Fatalf("expected Bar in generated types")
	}
}

func TestWriteFallbackTypesAndAliases(t *testing.T) {
	dir := t.TempDir()
	generated := map[string]struct{}{
		"KnownJSON":            {},
		"SanitizedMissingJSON": {},
	}
	fallbacks := []string{"Missing", "Opaque"}

	if err := writeFallbackTypes(dir, fallbacks, generated, testCodexCommit); err != nil {
		t.Fatalf("writeFallbackTypes error: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "fallback_gen.go"))
	if err != nil {
		t.Fatalf("read fallback file: %v", err)
	}
	if !strings.Contains(string(data), "Source codex commit: "+testCodexCommit) {
		t.Fatalf("expected codex commit header")
	}
	if !strings.Contains(string(data), "type Missing = SanitizedMissingJSON") {
		t.Fatalf("expected Missing alias fallback")
	}
	if !strings.Contains(string(data), "type Opaque interface{}") {
		t.Fatalf("expected Opaque interface fallback")
	}

	if err := writeProtocolAliases(dir, generated, fallbacks, testCodexCommit); err != nil {
		t.Fatalf("writeProtocolAliases error: %v", err)
	}
	aliasData, err := os.ReadFile(filepath.Join(dir, "aliases_gen.go"))
	if err != nil {
		t.Fatalf("read alias file: %v", err)
	}
	if !strings.Contains(string(aliasData), "type Known = KnownJSON") {
		t.Fatalf("expected alias for Known")
	}
}

func TestRenderHelpers(t *testing.T) {
	methods := []rpcMethod{
		{Method: "foo/bar", ParamsType: "FooParams", ResponseType: "FooResponse"},
	}
	client := string(renderClientRequests(methods, testCodexCommit))
	if !strings.Contains(client, "Source codex commit: "+testCodexCommit) {
		t.Fatalf("expected codex commit header")
	}
	if !strings.Contains(client, "func (c *Client) FooBar") {
		t.Fatalf("expected client method")
	}
	if !strings.Contains(client, "BuildClientRequest") {
		t.Fatalf("expected BuildClientRequest")
	}

	server := string(renderServerRequests(methods, testCodexCommit))
	if !strings.Contains(server, "unsupported server request") {
		t.Fatalf("expected server dispatch")
	}

	notes := string(renderNotifications([]rpcNotification{{Method: "turn/started", ParamsType: "TurnStartedNotification"}}, testCodexCommit))
	if !strings.Contains(notes, "turn/started") {
		t.Fatalf("expected notification method")
	}
}

func TestSchemaTitleAndDefinitions(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "schema.json")
	writeJSON(t, path, map[string]any{
		"title": "MySchema",
		"definitions": map[string]any{
			"Thing": map[string]any{"type": "object"},
		},
	})

	title, err := schemaTitle(path)
	if err != nil {
		t.Fatalf("schemaTitle error: %v", err)
	}
	if title != "MySchema" {
		t.Fatalf("unexpected title: %s", title)
	}

	defs, err := parseDefinitionNames(dir)
	if err != nil {
		t.Fatalf("parseDefinitionNames error: %v", err)
	}
	if _, ok := defs["MySchema"]; !ok {
		t.Fatalf("expected title in defs")
	}
	if _, ok := defs["Thing"]; !ok {
		t.Fatalf("expected definition in defs")
	}
}

func TestSchemaTitleErrors(t *testing.T) {
	if _, err := schemaTitle(filepath.Join(t.TempDir(), "missing.json")); err == nil {
		t.Fatalf("expected missing file error")
	}

	path := filepath.Join(t.TempDir(), "bad.json")
	if err := os.WriteFile(path, []byte("{bad"), 0o644); err != nil {
		t.Fatalf("write bad schema: %v", err)
	}
	if _, err := schemaTitle(path); err == nil {
		t.Fatalf("expected invalid json error")
	}
}

func TestParseDefinitionNamesInvalidJSON(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "bad.json"), []byte("{bad"), 0o644); err != nil {
		t.Fatalf("write bad schema: %v", err)
	}
	if _, err := parseDefinitionNames(dir); err == nil {
		t.Fatalf("expected invalid json error")
	}
}

func TestFindSchemaFiles(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a.json"), []byte("{}"), 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "b.txt"), []byte("x"), 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
	files, err := findSchemaFiles(dir)
	if err != nil {
		t.Fatalf("findSchemaFiles error: %v", err)
	}
	if len(files) != 1 || !strings.HasSuffix(files[0], "a.json") {
		t.Fatalf("unexpected files: %#v", files)
	}
}

func TestFindSchemaFilesMissingDir(t *testing.T) {
	if _, err := findSchemaFiles(filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Fatalf("expected missing directory error")
	}
}

func TestWriteFileAndExists(t *testing.T) {
	dir := t.TempDir()
	if err := writeFile(dir, "out.txt", []byte("hello")); err != nil {
		t.Fatalf("writeFile error: %v", err)
	}
	if !exists(filepath.Join(dir, "out.txt")) {
		t.Fatalf("expected file to exist")
	}
	if exists(filepath.Join(dir, "missing.txt")) {
		t.Fatalf("expected missing file to be absent")
	}
}

func TestSkipSchemaFiles(t *testing.T) {
	skip := skipSchemaFiles()
	if !skip["JSONRPCMessage.json"] {
		t.Fatalf("expected JSONRPCMessage.json to be skipped")
	}
	if skip["Other.json"] {
		t.Fatalf("unexpected skip for Other.json")
	}
}

func TestRepoRoot(t *testing.T) {
	root, err := repoRoot()
	if err != nil {
		t.Fatalf("repoRoot error: %v", err)
	}
	if !exists(filepath.Join(root, "go.mod")) {
		t.Fatalf("expected go.mod in repo root")
	}
	if !exists(filepath.Join(root, "internal", "codegen", "main.go")) {
		t.Fatalf("expected internal/codegen/main.go in repo root")
	}
}

func TestCodexRepoRootDefault(t *testing.T) {
	base := t.TempDir()
	sdkRoot := filepath.Join(base, "codex-sdk-go")
	codexRoot := filepath.Join(base, "codex")
	t.Setenv(codexRepoRootEnv, "")
	if err := os.MkdirAll(filepath.Join(sdkRoot, "internal"), 0o755); err != nil {
		t.Fatalf("mkdir sdk root: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(codexRoot, "codex-rs"), 0o755); err != nil {
		t.Fatalf("mkdir codex root: %v", err)
	}

	got, err := codexRepoRoot(sdkRoot)
	if err != nil {
		t.Fatalf("codexRepoRoot error: %v", err)
	}
	if got != codexRoot {
		t.Fatalf("unexpected codex root: got %q want %q", got, codexRoot)
	}
}

func TestCodexRepoRootFromEnv(t *testing.T) {
	base := t.TempDir()
	sdkRoot := filepath.Join(base, "codex-sdk-go")
	custom := filepath.Join("deps", "codex-source")
	expected := filepath.Join(sdkRoot, custom)
	if err := os.MkdirAll(filepath.Join(expected, "codex-rs"), 0o755); err != nil {
		t.Fatalf("mkdir codex root: %v", err)
	}

	t.Setenv(codexRepoRootEnv, custom)
	got, err := codexRepoRoot(sdkRoot)
	if err != nil {
		t.Fatalf("codexRepoRoot error: %v", err)
	}
	if got != expected {
		t.Fatalf("unexpected codex root: got %q want %q", got, expected)
	}
}

func TestCodexRepoRootErrors(t *testing.T) {
	base := t.TempDir()
	t.Setenv(codexRepoRootEnv, "missing")
	if _, err := codexRepoRoot(base); err == nil || !strings.Contains(err.Error(), codexRepoRootEnv) {
		t.Fatalf("expected env root error, got %v", err)
	}

	t.Setenv(codexRepoRootEnv, "")
	if _, err := codexRepoRoot(base); err == nil || !strings.Contains(err.Error(), "could not find codex checkout") {
		t.Fatalf("expected default root error, got %v", err)
	}
}

func TestCodexSourceForGenerationDefault(t *testing.T) {
	t.Setenv(codexRepoRefEnv, "")
	codexRoot := filepath.Join(t.TempDir(), "codex")

	got, cleanup, err := codexSourceForGeneration(codexRoot, t.TempDir())
	if err != nil {
		t.Fatalf("codexSourceForGeneration error: %v", err)
	}
	if got != codexRoot {
		t.Fatalf("unexpected source root: got %q want %q", got, codexRoot)
	}
	cleanup()
}

func TestCodexSourceForGenerationPinnedRef(t *testing.T) {
	base := t.TempDir()
	codexRoot := filepath.Join(base, "codex")
	tempDir := filepath.Join(base, "temp")
	ref := "v1.2.3"
	worktreeDir := filepath.Join(tempDir, "codex-source")
	var calls [][]string

	withGitCombinedOutput(t, func(args ...string) ([]byte, error) {
		calls = append(calls, append([]string(nil), args...))
		switch len(calls) {
		case 1:
			want := []string{"-C", codexRoot, "worktree", "add", "--detach", worktreeDir, ref}
			if strings.Join(args, "\x00") != strings.Join(want, "\x00") {
				t.Fatalf("unexpected add args: %#v", args)
			}
			if err := os.MkdirAll(filepath.Join(worktreeDir, "codex-rs"), 0o755); err != nil {
				t.Fatalf("mkdir worktree: %v", err)
			}
			return nil, nil
		case 2:
			want := []string{"-C", codexRoot, "worktree", "remove", "--force", worktreeDir}
			if strings.Join(args, "\x00") != strings.Join(want, "\x00") {
				t.Fatalf("unexpected remove args: %#v", args)
			}
			return nil, nil
		default:
			t.Fatalf("unexpected git call: %#v", args)
			return nil, nil
		}
	})

	t.Setenv(codexRepoRefEnv, ref)
	got, cleanup, err := codexSourceForGeneration(codexRoot, tempDir)
	if err != nil {
		t.Fatalf("codexSourceForGeneration error: %v", err)
	}
	if got != worktreeDir {
		t.Fatalf("unexpected source root: got %q want %q", got, worktreeDir)
	}
	cleanup()
	if len(calls) != 2 {
		t.Fatalf("expected add and remove calls, got %d", len(calls))
	}
}

func TestCodexSourceForGenerationPinnedRefError(t *testing.T) {
	withGitCombinedOutput(t, func(args ...string) ([]byte, error) {
		return []byte("unknown revision"), os.ErrNotExist
	})

	t.Setenv(codexRepoRefEnv, "missing-tag")
	_, _, err := codexSourceForGeneration(filepath.Join(t.TempDir(), "codex"), t.TempDir())
	if err == nil {
		t.Fatalf("expected error")
	}
	if !strings.Contains(err.Error(), "create codex worktree: unknown revision") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCodexSourceForGenerationPinnedRefMissingCodexRS(t *testing.T) {
	var removed bool
	withGitCombinedOutput(t, func(args ...string) ([]byte, error) {
		if len(args) >= 4 && args[2] == "worktree" && args[3] == "remove" {
			removed = true
		}
		return nil, nil
	})

	t.Setenv(codexRepoRefEnv, "ref-without-codex-rs")
	_, _, err := codexSourceForGeneration(filepath.Join(t.TempDir(), "codex"), t.TempDir())
	if err == nil || !strings.Contains(err.Error(), codexRepoRefEnv) {
		t.Fatalf("expected missing codex-rs error, got %v", err)
	}
	if !removed {
		t.Fatalf("expected cleanup to remove worktree")
	}
}

func TestCodexCommitHashError(t *testing.T) {
	_, err := codexCommitHash(t.TempDir())
	if err == nil {
		t.Fatalf("expected codexCommitHash error")
	}
}

func TestCodexCommitHashSuccessAndEmpty(t *testing.T) {
	withGitCombinedOutput(t, func(args ...string) ([]byte, error) {
		return []byte("abc123\n"), nil
	})
	hash, err := codexCommitHash(t.TempDir())
	if err != nil {
		t.Fatalf("codexCommitHash error: %v", err)
	}
	if hash != "abc123" {
		t.Fatalf("unexpected hash: %q", hash)
	}

	withGitCombinedOutput(t, func(args ...string) ([]byte, error) {
		return []byte(" \n"), nil
	})
	if _, err := codexCommitHash(t.TempDir()); err == nil || !strings.Contains(err.Error(), "empty hash") {
		t.Fatalf("expected empty hash error, got %v", err)
	}
}

func TestGitCommandError(t *testing.T) {
	err := gitCommandError("do thing", nil, errors.New("boom"))
	if err == nil || !strings.Contains(err.Error(), "boom") {
		t.Fatalf("expected wrapped error, got %v", err)
	}

	err = gitCommandError("do thing", []byte("details\n"), errors.New("boom"))
	if err == nil || err.Error() != "do thing: details" {
		t.Fatalf("unexpected command output error: %v", err)
	}
}

func TestSafeDoFile(t *testing.T) {
	dir := t.TempDir()
	schema := map[string]any{
		"title": "Foo",
		"type":  "object",
		"properties": map[string]any{
			"name": map[string]any{"type": "string"},
		},
	}
	path := filepath.Join(dir, "Foo.json")
	writeJSON(t, path, schema)

	gen, err := generator.New(generator.Config{
		DefaultPackageName: "protocol",
		DefaultOutputName:  "types_gen.go",
		OnlyModels:         true,
	})
	if err != nil {
		t.Fatalf("generator.New error: %v", err)
	}
	if err := safeDoFile(gen, path); err != nil {
		t.Fatalf("safeDoFile error: %v", err)
	}
	sources, err := gen.Sources()
	if err != nil {
		t.Fatalf("sources error: %v", err)
	}
	if len(sources) == 0 {
		t.Fatalf("expected generated sources")
	}
}

func TestParamsType(t *testing.T) {
	if got := paramsType(""); got != "struct{}" {
		t.Fatalf("unexpected params type: %s", got)
	}
	if got := paramsType("Foo"); got != "protocol.Foo" {
		t.Fatalf("unexpected params type: %s", got)
	}
}

func TestGenerateProtocolTypes(t *testing.T) {
	root := t.TempDir()
	schemaDir := filepath.Join(root, "schemas")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	writeJSON(t, filepath.Join(schemaDir, "Foo.json"), map[string]any{
		"title": "Foo",
		"type":  "object",
		"properties": map[string]any{
			"name": map[string]any{"type": "string"},
		},
	})

	if err := generateProtocolTypes(schemaDir, root, testCodexCommit); err != nil {
		t.Fatalf("generateProtocolTypes error: %v", err)
	}
	if !exists(filepath.Join(root, "protocol", "types_gen.go")) {
		t.Fatalf("expected types_gen.go output")
	}
	typesData, err := os.ReadFile(filepath.Join(root, "protocol", "types_gen.go"))
	if err != nil {
		t.Fatalf("read generated protocol file: %v", err)
	}
	if !strings.Contains(string(typesData), "Source codex commit: "+testCodexCommit) {
		t.Fatalf("expected codex commit header in protocol output")
	}
}

func TestGenerateProtocolTypesSkipsProtocolSchemas(t *testing.T) {
	root := t.TempDir()
	schemaDir := filepath.Join(root, "schemas")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	for _, name := range []string{schemaBundleFile, "JSONRPCRequest.json"} {
		if err := os.WriteFile(filepath.Join(schemaDir, name), []byte("{bad"), 0o644); err != nil {
			t.Fatalf("write skipped schema: %v", err)
		}
	}

	if err := generateProtocolTypes(schemaDir, root, testCodexCommit); err != nil {
		t.Fatalf("generateProtocolTypes error: %v", err)
	}
}

func TestGenerateProtocolTypesInvalidSchema(t *testing.T) {
	root := t.TempDir()
	schemaDir := filepath.Join(root, "schemas")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(schemaDir, "Bad.json"), []byte("{bad"), 0o644); err != nil {
		t.Fatalf("write bad schema: %v", err)
	}

	if err := generateProtocolTypes(schemaDir, root, testCodexCommit); err == nil {
		t.Fatalf("expected invalid schema error")
	}
}

func TestGenerateRPCStubs(t *testing.T) {
	root := t.TempDir()
	schemaDir := filepath.Join(root, "schemas")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	writeJSON(t, filepath.Join(schemaDir, "PingResponse.json"), map[string]any{
		"title": "PingResponse",
		"type":  "object",
	})
	writeJSON(t, filepath.Join(schemaDir, "ClientRequest.json"), map[string]any{
		"oneOf": []map[string]any{
			{
				"properties": map[string]any{
					"method": map[string]any{"enum": []string{"ping"}},
					"params": map[string]any{"type": "null"},
				},
			},
		},
	})
	writeJSON(t, filepath.Join(schemaDir, "ServerRequest.json"), map[string]any{
		"oneOf": []map[string]any{
			{
				"properties": map[string]any{
					"method": map[string]any{"enum": []string{"ping"}},
					"params": map[string]any{"type": "null"},
				},
			},
		},
	})
	writeJSON(t, filepath.Join(schemaDir, "ServerNotification.json"), map[string]any{
		"oneOf": []map[string]any{
			{
				"properties": map[string]any{
					"method": map[string]any{"enum": []string{"pong"}},
					"params": map[string]any{"type": "null"},
				},
			},
		},
	})

	if err := generateRPCStubs(schemaDir, root, testCodexCommit); err != nil {
		t.Fatalf("generateRPCStubs error: %v", err)
	}
	if !exists(filepath.Join(root, "rpc", "client_requests_gen.go")) {
		t.Fatalf("expected client_requests_gen.go output")
	}
	if !exists(filepath.Join(root, "rpc", "notifications_gen.go")) {
		t.Fatalf("expected notifications_gen.go output")
	}
	rpcData, err := os.ReadFile(filepath.Join(root, "rpc", "client_requests_gen.go"))
	if err != nil {
		t.Fatalf("read generated rpc file: %v", err)
	}
	if !strings.Contains(string(rpcData), "Source codex commit: "+testCodexCommit) {
		t.Fatalf("expected codex commit header in rpc output")
	}
}

func TestGenerateRPCStubsErrors(t *testing.T) {
	root := t.TempDir()
	if err := generateRPCStubs(filepath.Join(root, "missing"), root, testCodexCommit); err == nil {
		t.Fatalf("expected missing schema dir error")
	}

	schemaDir := filepath.Join(root, "schemas")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	writeJSON(t, filepath.Join(schemaDir, "ClientRequest.json"), map[string]any{
		"oneOf": []map[string]any{
			{"properties": map[string]any{
				"method": map[string]any{"enum": []string{"missing/response"}},
				"params": map[string]any{"type": "null"},
			}},
		},
	})
	writeJSON(t, filepath.Join(schemaDir, "ServerRequest.json"), map[string]any{"oneOf": []map[string]any{}})
	writeJSON(t, filepath.Join(schemaDir, "ServerNotification.json"), map[string]any{"oneOf": []map[string]any{}})
	if err := generateRPCStubs(schemaDir, root, testCodexCommit); err == nil || !strings.Contains(err.Error(), "unable to resolve response type") {
		t.Fatalf("expected unresolved response type error, got %v", err)
	}
}

func TestExportSchemasError(t *testing.T) {
	dir := t.TempDir()
	if err := exportSchemas(dir, filepath.Join(dir, "out")); err == nil {
		t.Fatalf("expected exportSchemas error")
	}
}

func writeJSON(t *testing.T, path string, payload any) {
	t.Helper()
	data, err := json.Marshal(payload)
	if err != nil {
		t.Fatalf("marshal error: %v", err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
}

func withGitCombinedOutput(t *testing.T, fn func(args ...string) ([]byte, error)) {
	t.Helper()
	original := gitCombinedOutput
	gitCombinedOutput = fn
	t.Cleanup(func() {
		gitCombinedOutput = original
	})
}
