package main

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/atombender/go-jsonschema/pkg/generator"
)

const (
	schemaBundleFile             = "codex_app_server_protocol.schemas.json"
	generatedHeaderBase          = "// DO NOT EDIT.\n// Generated by internal/codegen.\n"
	codexRepoRootEnv             = "CODEX_REPO_ROOT"
	codexRepoRefEnv              = "CODEX_REPO_REF"
	approvedUnionInventorySHA256 = "3e9c78fe0a86958dcbd03657f4d426277dc7427d1f0ca1d390b732d704359f23"
)

func main() {
	sdkRoot, err := repoRoot()
	if err != nil {
		fatal(err)
	}
	codexRoot, err := codexRepoRoot(sdkRoot)
	if err != nil {
		fatal(err)
	}

	tempDir, err := os.MkdirTemp("", "codex-schema-go-sdk-")
	if err != nil {
		fatal(err)
	}
	defer func() {
		_ = os.RemoveAll(tempDir)
	}()

	schemaDir := filepath.Join(tempDir, "schemas")
	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		fatal(err)
	}

	codexSourceRoot, cleanupCodexSource, err := codexSourceForGeneration(codexRoot, tempDir)
	if err != nil {
		fatal(err)
	}
	defer cleanupCodexSource()

	codexCommit, err := codexCommitHash(codexSourceRoot)
	if err != nil {
		fatal(err)
	}

	codexVersion, err := codexPackageVersion(codexSourceRoot)
	if err != nil {
		fatal(err)
	}

	if err := exportSchemas(codexSourceRoot, schemaDir); err != nil {
		fatal(err)
	}
	if err := validateUnionInventory(schemaDir); err != nil {
		fatal(err)
	}
	if _, err := collectDiscriminatedUnions(schemaDir, true); err != nil {
		fatal(err)
	}
	if err := generateProtocolTypes(schemaDir, sdkRoot, codexCommit, codexVersion); err != nil {
		fatal(err)
	}

	if err := generateRPCStubs(schemaDir, sdkRoot, codexCommit); err != nil {
		fatal(err)
	}
}

func exportSchemas(codexRoot, outDir string) error {
	cmd := exec.Command("cargo", "run", "-p", "codex-app-server-protocol", "--bin", "export", "--", "--out", outDir)
	cmd.Dir = filepath.Join(codexRoot, "codex-rs")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func generateProtocolTypes(schemaDir, repoRoot, codexCommit, codexVersion string) error {
	cfg := generator.Config{
		DefaultPackageName: "protocol",
		DefaultOutputName:  "types_gen.go",
		Tags:               []string{"json"},
		Capitalizations:    []string{"ID", "JSON", "RPC", "MCP", "HTTP", "URL", "SSE", "UUID"},
		OnlyModels:         true,
	}
	gen, err := generator.New(cfg)
	if err != nil {
		return err
	}

	schemaFiles, err := findSchemaFiles(schemaDir)
	if err != nil {
		return err
	}

	skip := skipSchemaFiles()
	var fallbacks []string
	var titles []string
	for _, file := range schemaFiles {
		if filepath.Base(file) == schemaBundleFile {
			continue
		}
		if skip[filepath.Base(file)] {
			continue
		}
		title, titleErr := schemaTitle(file)
		if titleErr != nil {
			return titleErr
		}
		if title != "" {
			titles = append(titles, title)
		}
		if err := safeDoFile(gen, file); err != nil {
			if title == "" {
				return fmt.Errorf("generate types from %s: %w", file, err)
			}
			fallbacks = append(fallbacks, title)
		}
	}

	sources, err := gen.Sources()
	if err != nil {
		return err
	}

	unions, err := collectDiscriminatedUnions(schemaDir, false)
	if err != nil {
		return err
	}
	manualTypes := manualProtocolTypes()
	for name := range unions {
		manualTypes[name] = struct{}{}
	}
	for name, src := range sources {
		sources[name] = filterManualTypeDeclarations(src, manualTypes)
	}
	if err := validateOpaqueGeneratedInterfaces(sources); err != nil {
		return err
	}

	outDir := filepath.Join(repoRoot, "protocol")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	generated := collectGeneratedTypes(sources)
	for name := range manualTypes {
		generated[name] = struct{}{}
	}
	for _, title := range titles {
		if title == "" {
			continue
		}
		if _, ok := generated[title]; ok {
			continue
		}
		if _, ok := generated[title+"JSON"]; ok {
			continue
		}
		fallbacks = append(fallbacks, title)
	}

	for name, src := range sources {
		normalized := normalizeGeneratedHeader(src, codexCommit)
		if err := writeGoFile(outDir, name, normalized); err != nil {
			return err
		}
	}

	if err := writeFallbackTypes(outDir, fallbacks, generated, codexCommit); err != nil {
		return err
	}

	if err := writeProtocolAliases(outDir, generated, fallbacks, codexCommit); err != nil {
		return err
	}

	if err := writeProtocolMetadata(outDir, codexCommit, codexVersion); err != nil {
		return err
	}

	unionSource := renderDiscriminatedUnionTypes(unions, codexCommit)
	unionPath := filepath.Join(outDir, "unions_gen.go")
	if len(unionSource) == 0 {
		_ = os.Remove(unionPath)
	} else if err := writeGoFile(outDir, filepath.Base(unionPath), unionSource); err != nil {
		return err
	}

	return nil
}

func filterManualTypeDeclarations(src []byte, manualTypes map[string]struct{}) []byte {
	lines := strings.SplitAfter(string(src), "\n")
	out := make([]string, 0, len(lines))
	for i := 0; i < len(lines); {
		line := lines[i]
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "type ") {
			fields := strings.Fields(trimmed)
			if len(fields) >= 2 {
				if _, ok := manualTypes[fields[1]]; ok {
					i++
					balance := strings.Count(line, "{") - strings.Count(line, "}")
					for i < len(lines) && balance > 0 {
						balance += strings.Count(lines[i], "{") - strings.Count(lines[i], "}")
						i++
					}
					continue
				}
			}
		}
		out = append(out, line)
		i++
	}
	return []byte(strings.Join(out, ""))
}

type schemaVariant struct {
	Properties map[string]schemaProperty `json:"properties"`
}

type schemaProperty struct {
	Enum  []string `json:"enum"`
	Ref   string   `json:"$ref"`
	Type  string   `json:"type"`
	Items *struct {
		Ref string `json:"$ref"`
	} `json:"items"`
}

type oneOfSchema struct {
	OneOf []schemaVariant `json:"oneOf"`
}

var requiredDiscriminatedUnions = map[string]struct{}{
	"ResponseItem":  {},
	"SandboxPolicy": {},
	"ThreadStatus":  {},
	"UserInput":     {},
}

// opaqueDiscriminatedUnionAllowlist preserves legacy interface-based API types
// whose wire variants are selected by server-request context rather than a
// stable payload discriminator available to SDK callers. New entries require
// review and a generator test.
var opaqueDiscriminatedUnionAllowlist = map[string]struct{}{
	"McpServerElicitationRequestParams": {},
}

type discriminatedUnionSchema struct {
	OneOf []struct {
		Properties map[string]json.RawMessage `json:"properties"`
		Required   []string                   `json:"required"`
	} `json:"oneOf"`
}

type discriminatedUnion struct {
	Name          string
	Discriminator string
	Kinds         []string
	Required      map[string][]string
}

func collectDiscriminatedUnions(schemaDir string, requireCore bool) (map[string]discriminatedUnion, error) {
	files, err := findSchemaFiles(schemaDir)
	if err != nil {
		return nil, err
	}
	found := make(map[string]discriminatedUnion)
	for _, file := range files {
		data, readErr := os.ReadFile(file)
		if readErr != nil {
			return nil, readErr
		}
		var doc struct {
			Title       string                     `json:"title"`
			OneOf       json.RawMessage            `json:"oneOf"`
			Definitions map[string]json.RawMessage `json:"definitions"`
		}
		if json.Unmarshal(data, &doc) != nil {
			continue
		}
		for name, raw := range doc.Definitions {
			if _, opaque := opaqueDiscriminatedUnionAllowlist[name]; opaque {
				continue
			}
			union, ok, unionErr := parseDiscriminatedUnion(name, raw)
			if unionErr != nil {
				return nil, fmt.Errorf("decode discriminated union %s from %s: %w", name, file, unionErr)
			}
			if ok {
				found[name] = union
			}
		}
		if doc.Title != "" && len(doc.OneOf) > 0 {
			if _, opaque := opaqueDiscriminatedUnionAllowlist[doc.Title]; opaque {
				continue
			}
			union, ok, unionErr := parseDiscriminatedUnion(doc.Title, data)
			if unionErr != nil {
				return nil, fmt.Errorf("decode discriminated union %s from %s: %w", doc.Title, file, unionErr)
			}
			if ok {
				found[doc.Title] = union
			}
		}
	}
	if !requireCore {
		return found, nil
	}
	for name := range requiredDiscriminatedUnions {
		if _, ok := found[name]; !ok {
			return nil, fmt.Errorf("required discriminated union %s is missing or unsupported", name)
		}
	}
	return found, nil
}

func parseDiscriminatedUnion(name string, data []byte) (discriminatedUnion, bool, error) {
	var schema discriminatedUnionSchema
	if err := json.Unmarshal(data, &schema); err != nil {
		return discriminatedUnion{}, false, err
	}
	if len(schema.OneOf) < 2 {
		return discriminatedUnion{}, false, nil
	}

	candidates := make(map[string][]string)
	for index, variant := range schema.OneOf {
		variantEnums := make(map[string]string)
		for propertyName, rawProperty := range variant.Properties {
			var property struct {
				Enum []string `json:"enum"`
			}
			if json.Unmarshal(rawProperty, &property) == nil && len(property.Enum) == 1 && property.Enum[0] != "" {
				variantEnums[propertyName] = property.Enum[0]
			}
		}
		if index == 0 {
			for propertyName, value := range variantEnums {
				candidates[propertyName] = []string{value}
			}
			continue
		}
		for propertyName, values := range candidates {
			value, ok := variantEnums[propertyName]
			if !ok {
				delete(candidates, propertyName)
				continue
			}
			candidates[propertyName] = append(values, value)
		}
	}
	if len(candidates) == 0 {
		return discriminatedUnion{}, false, nil
	}
	discriminator := "type"
	if _, ok := candidates[discriminator]; !ok {
		names := make([]string, 0, len(candidates))
		for candidate := range candidates {
			names = append(names, candidate)
		}
		sort.Strings(names)
		discriminator = names[0]
	}
	kinds := candidates[discriminator]
	required := make(map[string][]string, len(kinds))
	seen := make(map[string]struct{}, len(kinds))
	for _, kind := range kinds {
		if _, duplicate := seen[kind]; duplicate {
			return discriminatedUnion{}, false, fmt.Errorf("repeated %s discriminator %q", discriminator, kind)
		}
		seen[kind] = struct{}{}
	}
	for _, variant := range schema.OneOf {
		var discriminatorProperty struct {
			Enum []string `json:"enum"`
		}
		if json.Unmarshal(variant.Properties[discriminator], &discriminatorProperty) != nil || len(discriminatorProperty.Enum) != 1 {
			continue
		}
		fields := append([]string(nil), variant.Required...)
		sort.Strings(fields)
		required[discriminatorProperty.Enum[0]] = fields
	}
	sort.Strings(kinds)
	return discriminatedUnion{Name: name, Discriminator: discriminator, Kinds: kinds, Required: required}, true, nil
}

func renderDiscriminatedUnionTypes(unions map[string]discriminatedUnion, codexCommit string) []byte {
	if len(unions) == 0 {
		return nil
	}
	var b strings.Builder
	b.WriteString(generatedHeader(codexCommit))
	b.WriteString("package protocol\n\n")
	b.WriteString("import (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n\n")
	b.WriteString("func decodeDiscriminatedUnion(data []byte, discriminator string) (string, json.RawMessage, error) {\n")
	b.WriteString("\tif string(data) == \"null\" { return \"\", nil, nil }\n")
	b.WriteString("\tvar object map[string]json.RawMessage\n\tif err := json.Unmarshal(data, &object); err != nil { return \"\", nil, err }\n")
	b.WriteString("\trawKind, ok := object[discriminator]; if !ok { return \"\", nil, fmt.Errorf(\"missing %s discriminator\", discriminator) }\n")
	b.WriteString("\tvar kind string; if err := json.Unmarshal(rawKind, &kind); err != nil || kind == \"\" { return \"\", nil, fmt.Errorf(\"%s discriminator must be a non-empty string\", discriminator) }\n")
	b.WriteString("\treturn kind, append(json.RawMessage(nil), data...), nil\n}\n\n")
	b.WriteString("func requireDiscriminatedUnionFields(data json.RawMessage, union, kind string, fields ...string) error { var object map[string]json.RawMessage; if err := json.Unmarshal(data, &object); err != nil { return err }; for _, field := range fields { if _, ok := object[field]; !ok { return fmt.Errorf(\"%s variant %q is missing required field %q\", union, kind, field) } }; return nil }\n\n")

	names := make([]string, 0, len(unions))
	for name := range unions {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		union := unions[name]
		renderDiscriminatedUnion(&b, union.Name, union.Discriminator, union.Kinds, union.Required)
	}
	return []byte(b.String())
}

func renderDiscriminatedUnion(b *strings.Builder, name, discriminator string, kinds []string, required map[string][]string) {
	fmt.Fprintf(b, "// %sKind identifies a known %s variant.\n", name, name)
	fmt.Fprintf(b, "type %sKind string\n\nconst (\n", name)
	for _, kind := range kinds {
		fmt.Fprintf(b, "\t%sKind%s %sKind = %q\n", name, methodBaseName(kind), name, kind)
	}
	b.WriteString(")\n\n")
	fmt.Fprintf(b, "// %s preserves the complete JSON payload for a discriminated union.\n", name)
	fmt.Fprintf(b, "type %s struct { kind %sKind; raw json.RawMessage }\n\n", name, name)
	fmt.Fprintf(b, "// New%s validates the discriminator and wraps a JSON-marshalable %s value.\n", name, name)
	fmt.Fprintf(b, "func New%s(value any) (%s, error) { data, err := json.Marshal(value); if err != nil { return %s{}, err }; var result %s; err = json.Unmarshal(data, &result); return result, err }\n\n", name, name, name, name)
	fmt.Fprintf(b, "func (value *%s) UnmarshalJSON(data []byte) error { kind, raw, err := decodeDiscriminatedUnion(data, %q); if err != nil { return fmt.Errorf(\"decode %s: %%w\", err) }; switch %sKind(kind) {\n", name, discriminator, name, name)
	for _, kind := range kinds {
		fmt.Fprintf(b, "\tcase %sKind%s:\n", name, methodBaseName(kind))
		fields := required[kind]
		if len(fields) == 0 {
			b.WriteString("\t\t// No required payload fields beyond the discriminator.\n")
			continue
		}
		fmt.Fprintf(b, "\t\tif err := requireDiscriminatedUnionFields(raw, %q, kind", name)
		for _, field := range fields {
			fmt.Fprintf(b, ", %q", field)
		}
		b.WriteString("); err != nil { return err }\n")
	}
	fmt.Fprintf(b, "\t}; value.kind = %sKind(kind); value.raw = raw; return nil }\n\n", name)
	fmt.Fprintf(b, "func (value %s) MarshalJSON() ([]byte, error) { if len(value.raw) == 0 { return []byte(\"null\"), nil }; return append([]byte(nil), value.raw...), nil }\n\n", name)
	fmt.Fprintf(b, "// Kind returns the payload discriminator, including unknown future values.\nfunc (value %s) Kind() %sKind { return value.kind }\n\n", name, name)
	fmt.Fprintf(b, "// RawJSON returns a copy of the complete union payload.\nfunc (value %s) RawJSON() json.RawMessage { return append(json.RawMessage(nil), value.raw...) }\n\n", name)
	fmt.Fprintf(b, "// IsKnown reports whether the discriminator was present in the generation schema.\nfunc (value %s) IsKnown() bool { switch value.kind {\n", name)
	for _, kind := range kinds {
		fmt.Fprintf(b, "\tcase %sKind%s:\n\t\treturn true\n", name, methodBaseName(kind))
	}
	b.WriteString("\tdefault:\n\t\treturn false\n\t}\n}\n\n")
}

func generateRPCStubs(schemaDir, repoRoot, codexCommit string) error {
	defs, err := parseDefinitionNames(schemaDir)
	if err != nil {
		return err
	}

	clientMethods, err := loadMethods(filepath.Join(schemaDir, "ClientRequest.json"))
	if err != nil {
		return err
	}

	serverMethods, err := loadMethods(filepath.Join(schemaDir, "ServerRequest.json"))
	if err != nil {
		return err
	}

	notifications, err := loadNotifications(filepath.Join(schemaDir, "ServerNotification.json"))
	if err != nil {
		return err
	}

	clientRPC, err := buildRPCMethods(clientMethods, defs, clientResponseOverrides())
	if err != nil {
		return err
	}

	serverRPC, err := buildRPCMethods(serverMethods, defs, nil)
	if err != nil {
		return err
	}

	outDir := filepath.Join(repoRoot, "rpc")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	if err := writeGoFile(outDir, "client_requests_gen.go", renderClientRequests(clientRPC, codexCommit)); err != nil {
		return err
	}

	if err := writeGoFile(outDir, "server_requests_gen.go", renderServerRequests(serverRPC, codexCommit)); err != nil {
		return err
	}

	if err := writeGoFile(outDir, "notifications_gen.go", renderNotifications(notifications, codexCommit)); err != nil {
		return err
	}

	return nil
}

func parseDefinitionNames(schemaDir string) (map[string]struct{}, error) {
	files, err := findSchemaFiles(schemaDir)
	if err != nil {
		return nil, err
	}
	defs := make(map[string]struct{})
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			return nil, err
		}
		var doc struct {
			Title       string                     `json:"title"`
			Definitions map[string]json.RawMessage `json:"definitions"`
		}
		if err := json.Unmarshal(data, &doc); err != nil {
			return nil, err
		}
		if doc.Title != "" {
			defs[doc.Title] = struct{}{}
		}
		for name := range doc.Definitions {
			defs[name] = struct{}{}
		}
	}
	return defs, nil
}

func schemaTitle(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	var doc struct {
		Title string `json:"title"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		return "", err
	}
	return doc.Title, nil
}

func writeFallbackTypes(outDir string, titles []string, generated map[string]struct{}, codexCommit string) error {
	fallbackPath := filepath.Join(outDir, "fallback_gen.go")
	if len(titles) == 0 {
		_ = os.Remove(fallbackPath)
		return nil
	}

	unique := map[string]struct{}{}
	for _, title := range titles {
		if title != "" {
			unique[title] = struct{}{}
		}
	}

	aliases := map[string]string{}
	var names []string
	for name := range unique {
		if _, exists := generated[name]; exists {
			continue
		}
		if target, ok := sanitizedFallbackTarget(name, generated); ok {
			aliases[name] = target
			continue
		}
		if _, allowed := opaqueFallbackTypeAllowlist[name]; !allowed {
			return fmt.Errorf("schema %s requires an unreviewed interface{} fallback; add typed generation or an explicit opaque allowlist entry", name)
		}
		names = append(names, name)
	}
	if len(names) == 0 && len(aliases) == 0 {
		_ = os.Remove(fallbackPath)
		return nil
	}
	sort.Strings(names)
	aliasNames := make([]string, 0, len(aliases))
	for name := range aliases {
		aliasNames = append(aliasNames, name)
	}
	sort.Strings(aliasNames)

	var b strings.Builder
	b.WriteString(generatedHeader(codexCommit))
	b.WriteString("package protocol\n\n")
	b.WriteString("// Fallback types for schemas that failed to generate.\n")
	for _, name := range aliasNames {
		b.WriteString("type ")
		b.WriteString(name)
		b.WriteString(" = ")
		b.WriteString(aliases[name])
		b.WriteString("\n")
	}
	for _, name := range names {
		b.WriteString("type ")
		b.WriteString(name)
		b.WriteString(" interface{}\n")
	}

	return writeGoFile(outDir, filepath.Base(fallbackPath), []byte(b.String()))
}

var opaqueFallbackTypeAllowlist = map[string]struct{}{
	"ClientNotification":                              {},
	"CodexAppServerProtocolV2":                        {},
	"ConfigReadResponse":                              {},
	"ConfigWriteResponse":                             {},
	"FsChangedNotification":                           {},
	"FsWatchResponse":                                 {},
	"HookCompletedNotification":                       {},
	"HookStartedNotification":                         {},
	"HooksListResponse":                               {},
	"InitializeResponse":                              {},
	"ItemGuardianApprovalReviewCompletedNotification": {},
	"ItemGuardianApprovalReviewStartedNotification":   {},
	"ItemStartedNotification":                         {},
	"ListMcpServerStatusParams":                       {},
	"ListMcpServerStatusResponse":                     {},
	"MarketplaceAddResponse":                          {},
	"MarketplaceRemoveResponse":                       {},
	"MarketplaceUpgradeResponse":                      {},
	"McpResourceReadParams":                           {},
	"McpResourceReadResponse":                         {},
	"McpServerElicitationRequestParams":               {},
	"McpServerElicitationRequestResponse":             {},
	"McpServerOauthLoginCompletedNotification":        {},
	"McpServerOauthLoginParams":                       {},
	"McpServerOauthLoginResponse":                     {},
	"McpServerRefreshResponse":                        {},
	"McpServerStatusUpdatedNotification":              {},
	"McpServerToolCallParams":                         {},
	"McpServerToolCallResponse":                       {},
	"McpToolCallProgressNotification":                 {},
	"PluginInstalledResponse":                         {},
	"PluginListResponse":                              {},
	"PluginReadResponse":                              {},
	"PluginShareCheckoutResponse":                     {},
	"PluginShareListResponse":                         {},
	"ReviewStartResponse":                             {},
	"SkillsListResponse":                              {},
	"ThreadForkResponse":                              {},
	"ThreadListResponse":                              {},
	"ThreadMetadataUpdateResponse":                    {},
	"ThreadReadResponse":                              {},
	"ThreadRollbackResponse":                          {},
	"ThreadSettingsUpdatedNotification":               {},
	"ThreadStartedNotification":                       {},
	"ThreadUnarchiveResponse":                         {},
	"TurnStartResponse":                               {},
}

var opaqueGeneratedInterfaceAllowlist = map[string]struct{}{
	"AskForApproval":                            {},
	"AuthMode":                                  {},
	"CapabilityRootLocation":                    {},
	"ChatgptAuthTokensRefreshReason":            {},
	"CodexErrorInfo":                            {},
	"CommandExecOutputStream":                   {},
	"CommandExecutionApprovalDecision":          {},
	"ConsumeAccountRateLimitResetCreditOutcome": {},
	"DynamicToolNamespaceTool":                  {},
	"ExperimentalFeatureStage":                  {},
	"FileChangeApprovalDecision":                {},
	"FunctionCallOutputBody":                    {},
	"InputModality":                             {},
	"LocalShellAction":                          {},
	"MCPElicitationEnumSchema":                  {},
	"MCPElicitationMultiSelectEnumSchema":       {},
	"MCPElicitationPrimitiveSchema":             {},
	"MCPElicitationSingleSelectEnumSchema":      {},
	"MessagePhase":                              {},
	"MultiAgentMode":                            {},
	"ProcessOutputStream":                       {},
	"ReasoningItemReasoningSummary":             {},
	"ReasoningSummary":                          {},
	"RequestID":                                 {},
	"ResourceContent":                           {},
	"ReviewDecision":                            {},
	"ThreadListCwdFilter":                       {},
	"TurnItemsView":                             {},
}

func validateOpaqueGeneratedInterfaces(sources map[string][]byte) error {
	for _, source := range sources {
		for _, line := range strings.Split(string(source), "\n") {
			fields := strings.Fields(line)
			if len(fields) != 3 || fields[0] != "type" || fields[2] != "interface{}" {
				continue
			}
			if _, allowed := opaqueGeneratedInterfaceAllowlist[fields[1]]; !allowed {
				return fmt.Errorf("generated type %s is an unreviewed interface{}; add typed generation or an explicit opaque allowlist entry", fields[1])
			}
		}
	}
	return nil
}

func sanitizedFallbackTarget(name string, generated map[string]struct{}) (string, bool) {
	target := "Sanitized" + name + "JSON"
	if _, ok := generated[target]; ok {
		return target, true
	}
	return "", false
}

func collectGeneratedTypes(sources map[string][]byte) map[string]struct{} {
	generated := map[string]struct{}{}
	for _, src := range sources {
		lines := strings.Split(string(src), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "type ") {
				fields := strings.Fields(line)
				if len(fields) >= 2 {
					generated[fields[1]] = struct{}{}
				}
			}
		}
	}
	return generated
}

func writeProtocolAliases(outDir string, generated map[string]struct{}, fallbacks []string, codexCommit string) error {
	existing := map[string]struct{}{}
	for name := range generated {
		existing[name] = struct{}{}
	}
	for _, name := range fallbacks {
		if name != "" {
			existing[name] = struct{}{}
		}
	}

	aliases := map[string]string{}
	for name := range generated {
		if !strings.HasSuffix(name, "JSON") {
			continue
		}
		base := strings.TrimSuffix(name, "JSON")
		if base == "" {
			continue
		}
		if _, ok := existing[base]; ok {
			continue
		}
		aliases[base] = name
	}

	aliasPath := filepath.Join(outDir, "aliases_gen.go")
	if len(aliases) == 0 {
		_ = os.Remove(aliasPath)
		return nil
	}

	names := make([]string, 0, len(aliases))
	for name := range aliases {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(generatedHeader(codexCommit))
	b.WriteString("package protocol\n\n")
	b.WriteString("// Aliases for JSON-suffixed schema types.\n")
	for _, name := range names {
		b.WriteString("type ")
		b.WriteString(name)
		b.WriteString(" = ")
		b.WriteString(aliases[name])
		b.WriteString("\n")
	}

	return writeGoFile(outDir, filepath.Base(aliasPath), []byte(b.String()))
}

func skipSchemaFiles() map[string]bool {
	return map[string]bool{
		"JSONRPCMessage.json":      true,
		"JSONRPCRequest.json":      true,
		"JSONRPCResponse.json":     true,
		"JSONRPCNotification.json": true,
		"JSONRPCError.json":        true,
		"JSONRPCErrorError.json":   true,
		"EventMsg.json":            true,
		"RequestId.json":           true,
	}
}

func loadMethods(path string) ([]rpcMethod, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc oneOfSchema
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, err
	}

	methods := make([]rpcMethod, 0, len(doc.OneOf))
	for _, variant := range doc.OneOf {
		method := ""
		if prop, ok := variant.Properties["method"]; ok && len(prop.Enum) == 1 {
			method = prop.Enum[0]
		}
		if method == "" {
			continue
		}

		paramsType := ""
		if prop, ok := variant.Properties["params"]; ok {
			if prop.Ref != "" {
				paramsType = refName(prop.Ref)
			} else if prop.Type == "null" {
				paramsType = ""
			}
		}

		methods = append(methods, rpcMethod{
			Method:     method,
			ParamsType: paramsType,
		})
	}

	sort.Slice(methods, func(i, j int) bool { return methods[i].Method < methods[j].Method })

	return methods, nil
}

func loadNotifications(path string) ([]rpcNotification, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc oneOfSchema
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, err
	}

	notifications := make([]rpcNotification, 0, len(doc.OneOf))
	for _, variant := range doc.OneOf {
		method := ""
		if prop, ok := variant.Properties["method"]; ok && len(prop.Enum) == 1 {
			method = prop.Enum[0]
		}
		if method == "" {
			continue
		}

		paramsType := ""
		if prop, ok := variant.Properties["params"]; ok {
			if prop.Ref != "" {
				paramsType = refName(prop.Ref)
			} else if prop.Type == "null" {
				paramsType = ""
			}
		}

		notifications = append(notifications, rpcNotification{
			Method:     method,
			ParamsType: paramsType,
		})
	}

	sort.Slice(notifications, func(i, j int) bool { return notifications[i].Method < notifications[j].Method })

	return notifications, nil
}

func refName(ref string) string {
	const prefix = "#/definitions/"
	if strings.HasPrefix(ref, prefix) {
		return strings.TrimPrefix(ref, prefix)
	}
	return ref
}

type rpcMethod struct {
	Method       string
	ParamsType   string
	ResponseType string
}

type rpcNotification struct {
	Method     string
	ParamsType string
}

func buildRPCMethods(methods []rpcMethod, defs map[string]struct{}, overrides map[string]string) ([]rpcMethod, error) {
	resolved := make([]rpcMethod, 0, len(methods))
	for _, method := range methods {
		responseType, err := resolveResponseType(method, defs, overrides)
		if err != nil {
			return nil, err
		}
		method.ResponseType = responseType
		resolved = append(resolved, method)
	}
	return resolved, nil
}

func resolveResponseType(method rpcMethod, defs map[string]struct{}, overrides map[string]string) (string, error) {
	if overrides != nil {
		if override, ok := overrides[method.Method]; ok {
			return override, nil
		}
	}

	if method.ParamsType != "" {
		base := strings.TrimSuffix(method.ParamsType, "Params")
		candidate := base + "Response"
		if _, ok := defs[candidate]; ok {
			return candidate, nil
		}
	}

	candidate := methodBaseName(method.Method) + "Response"
	if _, ok := defs[candidate]; ok {
		return candidate, nil
	}

	return "", fmt.Errorf("unable to resolve response type for method %q", method.Method)
}

func methodBaseName(method string) string {
	parts := strings.FieldsFunc(method, func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9')
	})
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			b.WriteString(part[1:])
		}
	}
	return b.String()
}

func clientResponseOverrides() map[string]string {
	return map[string]string{
		"account/logout":                           "LogoutAccountResponse",
		"account/rateLimits/read":                  "GetAccountRateLimitsResponse",
		"account/usage/read":                       "GetAccountTokenUsageResponse",
		"account/workspaceMessages/read":           "GetWorkspaceMessagesResponse",
		"addConversationListener":                  "AddConversationSubscriptionResponse",
		"config/value/write":                       "ConfigWriteResponse",
		"config/batchWrite":                        "ConfigWriteResponse",
		"config/mcpServer/reload":                  "McpServerRefreshResponse",
		"externalAgentConfig/import/readHistories": "ExternalAgentConfigImportHistoriesReadResponse",
		"removeConversationListener":               "RemoveConversationSubscriptionResponse",
	}
}

func renderClientRequests(methods []rpcMethod, codexCommit string) []byte {
	var b strings.Builder
	b.WriteString(generatedHeader(codexCommit))
	b.WriteString("package rpc\n\n")
	b.WriteString("import (\n\t\"context\"\n\t\"encoding/json\"\n\n\t\"github.com/pmenglund/codex-sdk-go/protocol\"\n)\n\n")

	b.WriteString("// ClientRequests exposes typed JSON-RPC calls supported by the app-server.\n")
	b.WriteString("type ClientRequests interface {\n")
	for _, method := range methods {
		if method.ParamsType == "" {
			b.WriteString(fmt.Sprintf("\t%s(ctx context.Context) (*protocol.%s, error)\n", methodName(method.Method), method.ResponseType))
		} else {
			b.WriteString(fmt.Sprintf("\t%s(ctx context.Context, params %s) (*protocol.%s, error)\n", methodName(method.Method), paramsType(method.ParamsType), method.ResponseType))
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("// Client implements ClientRequests using JSON-RPC.\n")
	for _, method := range methods {
		if method.ParamsType == "" {
			b.WriteString(fmt.Sprintf("func (c *Client) %s(ctx context.Context) (*protocol.%s, error) {\n", methodName(method.Method), method.ResponseType))
		} else {
			b.WriteString(fmt.Sprintf("func (c *Client) %s(ctx context.Context, params %s) (*protocol.%s, error) {\n", methodName(method.Method), paramsType(method.ParamsType), method.ResponseType))
		}
		b.WriteString("\tvar result protocol.")
		b.WriteString(method.ResponseType)
		b.WriteString("\n")
		if method.ParamsType == "" {
			b.WriteString(fmt.Sprintf("\tif err := c.Call(ctx, %q, nil, &result); err != nil {\n", method.Method))
		} else {
			b.WriteString(fmt.Sprintf("\tif err := c.Call(ctx, %q, params, &result); err != nil {\n", method.Method))
		}
		b.WriteString("\t\treturn nil, err\n\t}\n\treturn &result, nil\n}\n\n")
	}

	b.WriteString("// BuildClientRequest builds a JSON-RPC request for a client method.\n")
	b.WriteString("func BuildClientRequest(method string, params any, id RequestID) (JSONRPCRequest, error) {\n")
	b.WriteString("\tvar raw json.RawMessage\n\tif params != nil {\n\t\tdata, err := json.Marshal(params)\n\t\tif err != nil {\n\t\t\treturn JSONRPCRequest{}, err\n\t\t}\n\t\traw = data\n\t}\n\treturn JSONRPCRequest{ID: id, Method: method, Params: raw}, nil\n}\n")

	return []byte(b.String())
}

func renderServerRequests(methods []rpcMethod, codexCommit string) []byte {
	var b strings.Builder
	b.WriteString(generatedHeader(codexCommit))
	b.WriteString("package rpc\n\n")
	b.WriteString("import (\n\t\"context\"\n\t\"encoding/json\"\n\n\t\"github.com/pmenglund/codex-sdk-go/protocol\"\n)\n\n")

	b.WriteString("// ServerRequestHandler handles requests initiated by the app-server.\n")
	b.WriteString("type ServerRequestHandler interface {\n")
	for _, method := range methods {
		if method.ParamsType == "" {
			b.WriteString(fmt.Sprintf("\t%s(ctx context.Context) (*protocol.%s, error)\n", methodName(method.Method), method.ResponseType))
		} else {
			b.WriteString(fmt.Sprintf("\t%s(ctx context.Context, params %s) (*protocol.%s, error)\n", methodName(method.Method), paramsType(method.ParamsType), method.ResponseType))
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("func dispatchServerRequest(ctx context.Context, handler ServerRequestHandler, req JSONRPCRequest) (result any, err error) {\n")
	b.WriteString("\tswitch req.Method {\n")
	for _, method := range methods {
		b.WriteString(fmt.Sprintf("\tcase %q:\n", method.Method))
		if method.ParamsType == "" {
			b.WriteString("\t\tresult, err = handler.")
			b.WriteString(methodName(method.Method))
			b.WriteString("(ctx)\n")
		} else {
			b.WriteString("\t\tvar params protocol.")
			b.WriteString(method.ParamsType)
			b.WriteString("\n")
			b.WriteString("\t\tif len(req.Params) > 0 {\n\t\t\tif err := json.Unmarshal(req.Params, &params); err != nil {\n\t\t\t\treturn nil, &ServerRequestParamsError{Method: req.Method, Err: err}\n\t\t\t}\n\t\t}\n")
			b.WriteString("\t\tresult, err = handler.")
			b.WriteString(methodName(method.Method))
			b.WriteString("(ctx, params)\n")
		}
		b.WriteString("\t\tif err != nil {\n\t\t\treturn nil, &ServerRequestHandlerError{Method: req.Method, Err: err}\n\t\t}\n\t\treturn result, nil\n")
	}
	b.WriteString("\tdefault:\n\t\treturn nil, &ServerRequestMethodError{Method: req.Method}\n\t}\n}\n")

	return []byte(b.String())
}

func renderNotifications(notifications []rpcNotification, codexCommit string) []byte {
	var b strings.Builder
	b.WriteString(generatedHeader(codexCommit))
	b.WriteString("package rpc\n\n")
	b.WriteString("import (\n\t\"encoding/json\"\n\n\t\"github.com/pmenglund/codex-sdk-go/protocol\"\n)\n\n")

	b.WriteString("// Notification represents a typed server notification.\n")
	b.WriteString("type Notification struct {\n\tMethod string\n\tParams any\n\tRaw json.RawMessage\n}\n\n")

	b.WriteString("type notificationParser func(json.RawMessage) (Notification, error)\n\n")
	b.WriteString("var notificationParsers = map[string]notificationParser{\n")
	for _, notification := range notifications {
		b.WriteString(fmt.Sprintf("\t%q: func(params json.RawMessage) (Notification, error) {\n", notification.Method))
		if notification.ParamsType == "" {
			b.WriteString(fmt.Sprintf("\t\treturn Notification{Method: %q, Params: nil, Raw: params}, nil\n", notification.Method))
		} else {
			b.WriteString("\t\tvar payload protocol.")
			b.WriteString(notification.ParamsType)
			b.WriteString("\n")
			b.WriteString("\t\tif len(params) > 0 {\n\t\t\tif err := json.Unmarshal(params, &payload); err != nil {\n\t\t\t\treturn Notification{Method: ")
			b.WriteString(fmt.Sprintf("%q", notification.Method))
			b.WriteString(", Raw: params}, err\n\t\t\t}\n\t\t}\n")
			b.WriteString("\t\treturn Notification{Method: ")
			b.WriteString(fmt.Sprintf("%q", notification.Method))
			b.WriteString(", Params: payload, Raw: params}, nil\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func parseServerNotification(method string, params json.RawMessage) (Notification, error) {\n")
	b.WriteString("\tif handler, ok := notificationParsers[method]; ok {\n\t\treturn handler(params)\n\t}\n")
	b.WriteString("\treturn Notification{Method: method, Raw: params}, nil\n}\n")

	return []byte(b.String())
}

func paramsType(name string) string {
	if name == "" {
		return "struct{}"
	}
	return "protocol." + name
}

func manualProtocolTypes() map[string]struct{} {
	return map[string]struct{}{
		"ApplyPatchApprovalParams":                {},
		"ApplyPatchApprovalResponse":              {},
		"CommandExecutionRequestApprovalParams":   {},
		"CommandExecutionRequestApprovalResponse": {},
		"ErrorNotification":                       {},
		"ExecCommandApprovalParams":               {},
		"ExecCommandApprovalResponse":             {},
		"FileChangeRequestApprovalParams":         {},
		"FileChangeRequestApprovalResponse":       {},
		"ItemCompletedNotification":               {},
		"PermissionsRequestApprovalParams":        {},
		"PermissionsRequestApprovalResponse":      {},
		"ResponseItem":                            {},
		"SandboxPolicy":                           {},
		"ThreadResumeResponse":                    {},
		"ThreadGoal":                              {},
		"ThreadGoalGetResponse":                   {},
		"ThreadGoalSetResponse":                   {},
		"ThreadGoalUpdatedNotification":           {},
		"ThreadForkParams":                        {},
		"ThreadResumeParams":                      {},
		"ThreadStartParams":                       {},
		"ThreadStartResponse":                     {},
		"ThreadStatus":                            {},
		"ToolRequestUserInputParams":              {},
		"ToolRequestUserInputResponse":            {},
		"TurnStartParams":                         {},
		"TurnStartParamsInputElem":                {},
		"UserInput":                               {},
		"TurnCompletedNotification":               {},
		"TurnStartedNotification":                 {},
	}
}

func methodName(method string) string {
	base := methodBaseName(method)
	if base == "" {
		return "Unknown"
	}
	return base
}

func normalizeGeneratedHeader(src []byte, codexCommit string) []byte {
	if len(src) == 0 {
		return src
	}
	parts := strings.SplitN(string(src), "\n", 2)
	if len(parts) == 0 {
		return src
	}
	header := strings.TrimSpace(parts[0])
	headerLower := strings.ToLower(header)
	if !strings.HasPrefix(headerLower, "// code generated") && !strings.HasPrefix(headerLower, "// generated") {
		return src
	}
	rest := ""
	if len(parts) > 1 {
		rest = strings.TrimLeft(parts[1], "\n")
	}
	return []byte(generatedHeader(codexCommit) + rest)
}

func generatedHeader(codexCommit string) string {
	return generatedHeaderBase + "// Source codex commit: " + codexCommit + "\n\n"
}

func writeProtocolMetadata(outDir, codexCommit, codexVersion string) error {
	var b strings.Builder
	b.WriteString(generatedHeader(codexCommit))
	b.WriteString("package protocol\n\n")
	b.WriteString("// GeneratedCodexCommit is the Codex source commit used to generate this protocol package.\n")
	b.WriteString(fmt.Sprintf("const GeneratedCodexCommit = %q\n\n", codexCommit))
	b.WriteString("// GeneratedCodexVersion is the Codex package version used to generate this protocol package.\n")
	b.WriteString(fmt.Sprintf("const GeneratedCodexVersion = %q\n", codexVersion))
	return writeGoFile(outDir, "metadata_gen.go", []byte(b.String()))
}

func writeFile(dir, name string, contents []byte) error {
	path := filepath.Join(dir, name)
	return os.WriteFile(path, contents, 0o644)
}

func writeGoFile(dir, name string, contents []byte) error {
	formatted, err := format.Source(contents)
	if err != nil {
		return fmt.Errorf("format generated Go file %s: %w", name, err)
	}
	return writeFile(dir, name, formatted)
}

func findSchemaFiles(schemaDir string) ([]string, error) {
	var files []string
	err := filepath.WalkDir(schemaDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if filepath.Ext(path) != ".json" {
			return nil
		}
		files = append(files, path)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	return files, nil
}

func validateUnionInventory(schemaDir string) error {
	files, err := findSchemaFiles(schemaDir)
	if err != nil {
		return err
	}
	unique := make(map[string]struct{})
	for _, file := range files {
		data, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		var node any
		if err := json.Unmarshal(data, &node); err != nil {
			return fmt.Errorf("decode union inventory from %s: %w", file, err)
		}
		collectUnionSchemas(node, unique)
	}
	items := make([]string, 0, len(unique))
	for item := range unique {
		items = append(items, item)
	}
	sort.Strings(items)
	digest := fmt.Sprintf("%x", sha256.Sum256([]byte(strings.Join(items, "\n"))))
	if os.Getenv("CODEX_PRINT_UNION_INVENTORY") == "1" {
		fmt.Fprintf(os.Stderr, "union inventory sha256 %s (%d unique schemas)\n", digest, len(items))
		for _, item := range items {
			fmt.Fprintf(os.Stderr, "%x  %s\n", sha256.Sum256([]byte(item)), item)
		}
	}
	if digest != approvedUnionInventorySHA256 {
		return fmt.Errorf("schema union inventory changed: got sha256 %s across %d unique union schemas; rerun with CODEX_PRINT_UNION_INVENTORY=1, review every new or changed oneOf/anyOf, then update approvedUnionInventorySHA256", digest, len(items))
	}
	return nil
}

func collectUnionSchemas(node any, unique map[string]struct{}) {
	switch value := node.(type) {
	case map[string]any:
		if _, hasOneOf := value["oneOf"]; hasOneOf {
			if data, err := json.Marshal(value); err == nil {
				unique[string(data)] = struct{}{}
			}
		}
		if _, hasAnyOf := value["anyOf"]; hasAnyOf {
			if data, err := json.Marshal(value); err == nil {
				unique[string(data)] = struct{}{}
			}
		}
		for _, child := range value {
			collectUnionSchemas(child, unique)
		}
	case []any:
		for _, child := range value {
			collectUnionSchemas(child, unique)
		}
	}
}

func safeDoFile(gen *generator.Generator, file string) (err error) {
	sanitized, cleanup, err := sanitizeSchemaFile(file)
	if err != nil {
		return err
	}
	defer cleanup()
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic: %v", r)
		}
	}()
	return gen.DoFile(sanitized)
}

func sanitizeSchemaFile(path string) (string, func(), error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", nil, err
	}
	var node any
	if err := json.Unmarshal(data, &node); err != nil {
		return "", nil, err
	}
	stripSubschemas(node)
	out, err := json.Marshal(node)
	if err != nil {
		return "", nil, err
	}
	sanitizedName := "sanitized-" + filepath.Base(path)
	sanitizedPath := filepath.Join(filepath.Dir(path), sanitizedName)
	if err := os.WriteFile(sanitizedPath, out, 0o644); err != nil {
		return "", nil, err
	}
	cleanup := func() {
		_ = os.Remove(sanitizedPath)
	}
	return sanitizedPath, cleanup, nil
}

func stripSubschemas(node any) {
	switch value := node.(type) {
	case map[string]any:
		delete(value, "oneOf")
		delete(value, "anyOf")
		for _, child := range value {
			stripSubschemas(child)
		}
	case []any:
		for _, child := range value {
			stripSubschemas(child)
		}
	}
}

func repoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}

	// Walk up until we find this repository root.
	current := cwd
	for {
		if exists(filepath.Join(current, "go.mod")) && exists(filepath.Join(current, "internal", "codegen", "main.go")) {
			return current, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			break
		}
		current = parent
	}

	return "", fmt.Errorf("unable to locate codex-sdk-go repo root from %s", cwd)
}

func codexRepoRoot(sdkRoot string) (string, error) {
	if configured := strings.TrimSpace(os.Getenv(codexRepoRootEnv)); configured != "" {
		root := configured
		if !filepath.IsAbs(root) {
			root = filepath.Join(sdkRoot, root)
		}
		if !exists(filepath.Join(root, "codex-rs")) {
			return "", fmt.Errorf("%s=%q does not contain codex-rs", codexRepoRootEnv, configured)
		}
		return root, nil
	}

	defaultRoot := filepath.Join(sdkRoot, "..", "codex")
	if exists(filepath.Join(defaultRoot, "codex-rs")) {
		return defaultRoot, nil
	}

	return "", fmt.Errorf("could not find codex checkout at %s (set %s)", defaultRoot, codexRepoRootEnv)
}

func codexSourceForGeneration(codexRoot, tempDir string) (string, func(), error) {
	ref := strings.TrimSpace(os.Getenv(codexRepoRefEnv))
	if ref == "" {
		return codexRoot, func() {}, nil
	}

	worktreeDir := filepath.Join(tempDir, "codex-source")
	if err := addCodexWorktree(codexRoot, worktreeDir, ref); err != nil {
		return "", nil, err
	}

	cleanup := func() {
		if err := removeCodexWorktree(codexRoot, worktreeDir); err != nil {
			fmt.Fprintf(os.Stderr, "warning: remove codex worktree: %v\n", err)
		}
	}

	if !exists(filepath.Join(worktreeDir, "codex-rs")) {
		cleanup()
		return "", nil, fmt.Errorf("%s=%q does not contain codex-rs", codexRepoRefEnv, ref)
	}

	return worktreeDir, cleanup, nil
}

func addCodexWorktree(codexRoot, worktreeDir, ref string) error {
	out, err := gitCombinedOutput("-C", codexRoot, "worktree", "add", "--detach", worktreeDir, ref)
	if err != nil {
		return gitCommandError("create codex worktree", out, err)
	}
	return nil
}

func removeCodexWorktree(codexRoot, worktreeDir string) error {
	out, err := gitCombinedOutput("-C", codexRoot, "worktree", "remove", "--force", worktreeDir)
	if err != nil {
		return gitCommandError("remove codex worktree", out, err)
	}
	return nil
}

func codexCommitHash(codexRoot string) (string, error) {
	out, err := gitCombinedOutput("-C", codexRoot, "rev-parse", "HEAD")
	if err != nil {
		return "", gitCommandError("resolve codex commit hash", out, err)
	}
	hash := strings.TrimSpace(string(out))
	if hash == "" {
		return "", fmt.Errorf("resolve codex commit hash: empty hash")
	}
	return hash, nil
}

func codexPackageVersion(codexRoot string) (string, error) {
	data, err := os.ReadFile(filepath.Join(codexRoot, "codex-rs", "Cargo.toml"))
	if err != nil {
		return "", fmt.Errorf("read codex Cargo.toml: %w", err)
	}
	version := parseWorkspacePackageVersion(string(data))
	if version == "" {
		return "", errors.New("resolve codex package version: [workspace.package] version not found")
	}
	return version, nil
}

func parseWorkspacePackageVersion(contents string) string {
	inWorkspacePackage := false
	for _, line := range strings.Split(contents, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") {
			inWorkspacePackage = line == "[workspace.package]"
			continue
		}
		if !inWorkspacePackage || !strings.HasPrefix(line, "version") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 || strings.TrimSpace(parts[0]) != "version" {
			continue
		}
		return strings.Trim(strings.TrimSpace(parts[1]), `"'`)
	}
	return ""
}

func gitCommandError(action string, out []byte, err error) error {
	msg := strings.TrimSpace(string(out))
	if msg == "" {
		return fmt.Errorf("%s: %w", action, err)
	}
	return fmt.Errorf("%s: %s", action, msg)
}

var gitCombinedOutput = func(args ...string) ([]byte, error) {
	cmd := exec.Command("git", args...)
	return cmd.CombinedOutput()
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
