// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 5d1fbf26c43abc65a203928b2e31561cb039e06d

package protocol

// AccountLoginCompletedNotification is a generated alias for a Codex app-server protocol type.
// Fallback types for schemas that failed to generate.
type AccountLoginCompletedNotification = SanitizedAccountLoginCompletedNotificationJSON

// AccountRateLimitsUpdatedNotification is a generated alias for a Codex app-server protocol type.
type AccountRateLimitsUpdatedNotification = SanitizedAccountRateLimitsUpdatedNotificationJSON

// AccountUpdatedNotification is a generated alias for a Codex app-server protocol type.
type AccountUpdatedNotification = SanitizedAccountUpdatedNotificationJSON

// AgentMessageDeltaNotification is a generated alias for a Codex app-server protocol type.
type AgentMessageDeltaNotification = SanitizedAgentMessageDeltaNotificationJSON

// AppListUpdatedNotification is a generated alias for a Codex app-server protocol type.
type AppListUpdatedNotification = SanitizedAppListUpdatedNotificationJSON

// AppsListResponse is a generated alias for a Codex app-server protocol type.
type AppsListResponse = SanitizedAppsListResponseJSON

// AttestationGenerateParams is a generated alias for a Codex app-server protocol type.
type AttestationGenerateParams = SanitizedAttestationGenerateParamsJSON

// AttestationGenerateResponse is a generated alias for a Codex app-server protocol type.
type AttestationGenerateResponse = SanitizedAttestationGenerateResponseJSON

// CancelLoginAccountResponse is a generated alias for a Codex app-server protocol type.
type CancelLoginAccountResponse = SanitizedCancelLoginAccountResponseJSON

// ChatgptAuthTokensRefreshParams is a generated alias for a Codex app-server protocol type.
type ChatgptAuthTokensRefreshParams = SanitizedChatgptAuthTokensRefreshParamsJSON

// ChatgptAuthTokensRefreshResponse is a generated alias for a Codex app-server protocol type.
type ChatgptAuthTokensRefreshResponse = SanitizedChatgptAuthTokensRefreshResponseJSON

// CommandExecOutputDeltaNotification is a generated alias for a Codex app-server protocol type.
type CommandExecOutputDeltaNotification = SanitizedCommandExecOutputDeltaNotificationJSON

// CommandExecResizeResponse is a generated alias for a Codex app-server protocol type.
type CommandExecResizeResponse = SanitizedCommandExecResizeResponseJSON

// CommandExecResponse is a generated alias for a Codex app-server protocol type.
type CommandExecResponse = SanitizedCommandExecResponseJSON

// CommandExecTerminateResponse is a generated alias for a Codex app-server protocol type.
type CommandExecTerminateResponse = SanitizedCommandExecTerminateResponseJSON

// CommandExecWriteResponse is a generated alias for a Codex app-server protocol type.
type CommandExecWriteResponse = SanitizedCommandExecWriteResponseJSON

// CommandExecutionOutputDeltaNotification is a generated alias for a Codex app-server protocol type.
type CommandExecutionOutputDeltaNotification = SanitizedCommandExecutionOutputDeltaNotificationJSON

// ConfigRequirementsReadResponse is a generated alias for a Codex app-server protocol type.
type ConfigRequirementsReadResponse = SanitizedConfigRequirementsReadResponseJSON

// ConfigWarningNotification is a generated alias for a Codex app-server protocol type.
type ConfigWarningNotification = SanitizedConfigWarningNotificationJSON

// ConsumeAccountRateLimitResetCreditResponse is a generated alias for a Codex app-server protocol type.
type ConsumeAccountRateLimitResetCreditResponse = SanitizedConsumeAccountRateLimitResetCreditResponseJSON

// ContextCompactedNotification is a generated alias for a Codex app-server protocol type.
type ContextCompactedNotification = SanitizedContextCompactedNotificationJSON

// DeprecationNoticeNotification is a generated alias for a Codex app-server protocol type.
type DeprecationNoticeNotification = SanitizedDeprecationNoticeNotificationJSON

// DynamicToolCallParams is a generated alias for a Codex app-server protocol type.
type DynamicToolCallParams = SanitizedDynamicToolCallParamsJSON

// DynamicToolCallResponse is a generated alias for a Codex app-server protocol type.
type DynamicToolCallResponse = SanitizedDynamicToolCallResponseJSON

// ExperimentalFeatureEnablementSetResponse is a generated alias for a Codex app-server protocol type.
type ExperimentalFeatureEnablementSetResponse = SanitizedExperimentalFeatureEnablementSetResponseJSON

// ExperimentalFeatureListResponse is a generated alias for a Codex app-server protocol type.
type ExperimentalFeatureListResponse = SanitizedExperimentalFeatureListResponseJSON

// ExternalAgentConfigDetectResponse is a generated alias for a Codex app-server protocol type.
type ExternalAgentConfigDetectResponse = SanitizedExternalAgentConfigDetectResponseJSON

// ExternalAgentConfigImportCompletedNotification is a generated alias for a Codex app-server protocol type.
type ExternalAgentConfigImportCompletedNotification = SanitizedExternalAgentConfigImportCompletedNotificationJSON

// ExternalAgentConfigImportHistoriesReadResponse is a generated alias for a Codex app-server protocol type.
type ExternalAgentConfigImportHistoriesReadResponse = SanitizedExternalAgentConfigImportHistoriesReadResponseJSON

// ExternalAgentConfigImportProgressNotification is a generated alias for a Codex app-server protocol type.
type ExternalAgentConfigImportProgressNotification = SanitizedExternalAgentConfigImportProgressNotificationJSON

// ExternalAgentConfigImportResponse is a generated alias for a Codex app-server protocol type.
type ExternalAgentConfigImportResponse = SanitizedExternalAgentConfigImportResponseJSON

// FeedbackUploadResponse is a generated alias for a Codex app-server protocol type.
type FeedbackUploadResponse = SanitizedFeedbackUploadResponseJSON

// FileChangeOutputDeltaNotification is a generated alias for a Codex app-server protocol type.
type FileChangeOutputDeltaNotification = SanitizedFileChangeOutputDeltaNotificationJSON

// FileChangePatchUpdatedNotification is a generated alias for a Codex app-server protocol type.
type FileChangePatchUpdatedNotification = SanitizedFileChangePatchUpdatedNotificationJSON

// FsCopyResponse is a generated alias for a Codex app-server protocol type.
type FsCopyResponse = SanitizedFsCopyResponseJSON

// FsCreateDirectoryResponse is a generated alias for a Codex app-server protocol type.
type FsCreateDirectoryResponse = SanitizedFsCreateDirectoryResponseJSON

// FsGetMetadataResponse is a generated alias for a Codex app-server protocol type.
type FsGetMetadataResponse = SanitizedFsGetMetadataResponseJSON

// FsReadDirectoryResponse is a generated alias for a Codex app-server protocol type.
type FsReadDirectoryResponse = SanitizedFsReadDirectoryResponseJSON

// FsReadFileResponse is a generated alias for a Codex app-server protocol type.
type FsReadFileResponse = SanitizedFsReadFileResponseJSON

// FsRemoveResponse is a generated alias for a Codex app-server protocol type.
type FsRemoveResponse = SanitizedFsRemoveResponseJSON

// FsUnwatchResponse is a generated alias for a Codex app-server protocol type.
type FsUnwatchResponse = SanitizedFsUnwatchResponseJSON

// FsWriteFileResponse is a generated alias for a Codex app-server protocol type.
type FsWriteFileResponse = SanitizedFsWriteFileResponseJSON

// FuzzyFileSearchResponse is a generated alias for a Codex app-server protocol type.
type FuzzyFileSearchResponse = SanitizedFuzzyFileSearchResponseJSON

// FuzzyFileSearchSessionCompletedNotification is a generated alias for a Codex app-server protocol type.
type FuzzyFileSearchSessionCompletedNotification = SanitizedFuzzyFileSearchSessionCompletedNotificationJSON

// FuzzyFileSearchSessionUpdatedNotification is a generated alias for a Codex app-server protocol type.
type FuzzyFileSearchSessionUpdatedNotification = SanitizedFuzzyFileSearchSessionUpdatedNotificationJSON

// GetAccountRateLimitsResponse is a generated alias for a Codex app-server protocol type.
type GetAccountRateLimitsResponse = SanitizedGetAccountRateLimitsResponseJSON

// GetAccountResponse is a generated alias for a Codex app-server protocol type.
type GetAccountResponse = SanitizedGetAccountResponseJSON

// GetAccountTokenUsageResponse is a generated alias for a Codex app-server protocol type.
type GetAccountTokenUsageResponse = SanitizedGetAccountTokenUsageResponseJSON

// GetWorkspaceMessagesResponse is a generated alias for a Codex app-server protocol type.
type GetWorkspaceMessagesResponse = SanitizedGetWorkspaceMessagesResponseJSON

// GuardianWarningNotification is a generated alias for a Codex app-server protocol type.
type GuardianWarningNotification = SanitizedGuardianWarningNotificationJSON

// ListMCPServerStatusResponse is a generated alias for a Codex app-server protocol type.
type ListMCPServerStatusResponse = SanitizedListMCPServerStatusResponseJSON

// LogoutAccountResponse is a generated alias for a Codex app-server protocol type.
type LogoutAccountResponse = SanitizedLogoutAccountResponseJSON

// MCPResourceReadResponse is a generated alias for a Codex app-server protocol type.
type MCPResourceReadResponse = SanitizedMCPResourceReadResponseJSON

// MCPServerElicitationRequestResponse is a generated alias for a Codex app-server protocol type.
type MCPServerElicitationRequestResponse = SanitizedMCPServerElicitationRequestResponseJSON

// MCPServerOAuthLoginCompletedNotification is a generated alias for a Codex app-server protocol type.
type MCPServerOAuthLoginCompletedNotification = SanitizedMCPServerOAuthLoginCompletedNotificationJSON

// MCPServerOAuthLoginResponse is a generated alias for a Codex app-server protocol type.
type MCPServerOAuthLoginResponse = SanitizedMCPServerOAuthLoginResponseJSON

// MCPServerRefreshResponse is a generated alias for a Codex app-server protocol type.
type MCPServerRefreshResponse = SanitizedMCPServerRefreshResponseJSON

// MCPServerStatusUpdatedNotification is a generated alias for a Codex app-server protocol type.
type MCPServerStatusUpdatedNotification = SanitizedMCPServerStatusUpdatedNotificationJSON

// MCPServerToolCallResponse is a generated alias for a Codex app-server protocol type.
type MCPServerToolCallResponse = SanitizedMCPServerToolCallResponseJSON

// MCPToolCallProgressNotification is a generated alias for a Codex app-server protocol type.
type MCPToolCallProgressNotification = SanitizedMCPToolCallProgressNotificationJSON

// ModelListResponse is a generated alias for a Codex app-server protocol type.
type ModelListResponse = SanitizedModelListResponseJSON

// ModelProviderCapabilitiesReadResponse is a generated alias for a Codex app-server protocol type.
type ModelProviderCapabilitiesReadResponse = SanitizedModelProviderCapabilitiesReadResponseJSON

// ModelReroutedNotification is a generated alias for a Codex app-server protocol type.
type ModelReroutedNotification = SanitizedModelReroutedNotificationJSON

// ModelSafetyBufferingUpdatedNotification is a generated alias for a Codex app-server protocol type.
type ModelSafetyBufferingUpdatedNotification = SanitizedModelSafetyBufferingUpdatedNotificationJSON

// ModelVerificationNotification is a generated alias for a Codex app-server protocol type.
type ModelVerificationNotification = SanitizedModelVerificationNotificationJSON

// PermissionProfileListResponse is a generated alias for a Codex app-server protocol type.
type PermissionProfileListResponse = SanitizedPermissionProfileListResponseJSON

// PlanDeltaNotification is a generated alias for a Codex app-server protocol type.
type PlanDeltaNotification = SanitizedPlanDeltaNotificationJSON

// PluginInstallResponse is a generated alias for a Codex app-server protocol type.
type PluginInstallResponse = SanitizedPluginInstallResponseJSON

// PluginShareDeleteResponse is a generated alias for a Codex app-server protocol type.
type PluginShareDeleteResponse = SanitizedPluginShareDeleteResponseJSON

// PluginShareSaveResponse is a generated alias for a Codex app-server protocol type.
type PluginShareSaveResponse = SanitizedPluginShareSaveResponseJSON

// PluginShareUpdateTargetsResponse is a generated alias for a Codex app-server protocol type.
type PluginShareUpdateTargetsResponse = SanitizedPluginShareUpdateTargetsResponseJSON

// PluginSkillReadResponse is a generated alias for a Codex app-server protocol type.
type PluginSkillReadResponse = SanitizedPluginSkillReadResponseJSON

// PluginUninstallResponse is a generated alias for a Codex app-server protocol type.
type PluginUninstallResponse = SanitizedPluginUninstallResponseJSON

// ProcessExitedNotification is a generated alias for a Codex app-server protocol type.
type ProcessExitedNotification = SanitizedProcessExitedNotificationJSON

// ProcessOutputDeltaNotification is a generated alias for a Codex app-server protocol type.
type ProcessOutputDeltaNotification = SanitizedProcessOutputDeltaNotificationJSON

// RawResponseItemCompletedNotification is a generated alias for a Codex app-server protocol type.
type RawResponseItemCompletedNotification = SanitizedRawResponseItemCompletedNotificationJSON

// ReasoningSummaryPartAddedNotification is a generated alias for a Codex app-server protocol type.
type ReasoningSummaryPartAddedNotification = SanitizedReasoningSummaryPartAddedNotificationJSON

// ReasoningSummaryTextDeltaNotification is a generated alias for a Codex app-server protocol type.
type ReasoningSummaryTextDeltaNotification = SanitizedReasoningSummaryTextDeltaNotificationJSON

// ReasoningTextDeltaNotification is a generated alias for a Codex app-server protocol type.
type ReasoningTextDeltaNotification = SanitizedReasoningTextDeltaNotificationJSON

// RemoteControlStatusChangedNotification is a generated alias for a Codex app-server protocol type.
type RemoteControlStatusChangedNotification = SanitizedRemoteControlStatusChangedNotificationJSON

// SendAddCreditsNudgeEmailResponse is a generated alias for a Codex app-server protocol type.
type SendAddCreditsNudgeEmailResponse = SanitizedSendAddCreditsNudgeEmailResponseJSON

// ServerRequestResolvedNotification is a generated alias for a Codex app-server protocol type.
type ServerRequestResolvedNotification = SanitizedServerRequestResolvedNotificationJSON

// SkillsChangedNotification is a generated alias for a Codex app-server protocol type.
type SkillsChangedNotification = SanitizedSkillsChangedNotificationJSON

// SkillsConfigWriteResponse is a generated alias for a Codex app-server protocol type.
type SkillsConfigWriteResponse = SanitizedSkillsConfigWriteResponseJSON

// SkillsExtraRootsSetResponse is a generated alias for a Codex app-server protocol type.
type SkillsExtraRootsSetResponse = SanitizedSkillsExtraRootsSetResponseJSON

// TerminalInteractionNotification is a generated alias for a Codex app-server protocol type.
type TerminalInteractionNotification = SanitizedTerminalInteractionNotificationJSON

// ThreadApproveGuardianDeniedActionResponse is a generated alias for a Codex app-server protocol type.
type ThreadApproveGuardianDeniedActionResponse = SanitizedThreadApproveGuardianDeniedActionResponseJSON

// ThreadArchiveResponse is a generated alias for a Codex app-server protocol type.
type ThreadArchiveResponse = SanitizedThreadArchiveResponseJSON

// ThreadArchivedNotification is a generated alias for a Codex app-server protocol type.
type ThreadArchivedNotification = SanitizedThreadArchivedNotificationJSON

// ThreadClosedNotification is a generated alias for a Codex app-server protocol type.
type ThreadClosedNotification = SanitizedThreadClosedNotificationJSON

// ThreadCompactStartResponse is a generated alias for a Codex app-server protocol type.
type ThreadCompactStartResponse = SanitizedThreadCompactStartResponseJSON

// ThreadDeleteResponse is a generated alias for a Codex app-server protocol type.
type ThreadDeleteResponse = SanitizedThreadDeleteResponseJSON

// ThreadDeletedNotification is a generated alias for a Codex app-server protocol type.
type ThreadDeletedNotification = SanitizedThreadDeletedNotificationJSON

// ThreadGoalClearResponse is a generated alias for a Codex app-server protocol type.
type ThreadGoalClearResponse = SanitizedThreadGoalClearResponseJSON

// ThreadGoalClearedNotification is a generated alias for a Codex app-server protocol type.
type ThreadGoalClearedNotification = SanitizedThreadGoalClearedNotificationJSON

// ThreadInjectItemsResponse is a generated alias for a Codex app-server protocol type.
type ThreadInjectItemsResponse = SanitizedThreadInjectItemsResponseJSON

// ThreadLoadedListResponse is a generated alias for a Codex app-server protocol type.
type ThreadLoadedListResponse = SanitizedThreadLoadedListResponseJSON

// ThreadNameUpdatedNotification is a generated alias for a Codex app-server protocol type.
type ThreadNameUpdatedNotification = SanitizedThreadNameUpdatedNotificationJSON

// ThreadRealtimeClosedNotification is a generated alias for a Codex app-server protocol type.
type ThreadRealtimeClosedNotification = SanitizedThreadRealtimeClosedNotificationJSON

// ThreadRealtimeErrorNotification is a generated alias for a Codex app-server protocol type.
type ThreadRealtimeErrorNotification = SanitizedThreadRealtimeErrorNotificationJSON

// ThreadRealtimeItemAddedNotification is a generated alias for a Codex app-server protocol type.
type ThreadRealtimeItemAddedNotification = SanitizedThreadRealtimeItemAddedNotificationJSON

// ThreadRealtimeOutputAudioDeltaNotification is a generated alias for a Codex app-server protocol type.
type ThreadRealtimeOutputAudioDeltaNotification = SanitizedThreadRealtimeOutputAudioDeltaNotificationJSON

// ThreadRealtimeSdpNotification is a generated alias for a Codex app-server protocol type.
type ThreadRealtimeSdpNotification = SanitizedThreadRealtimeSdpNotificationJSON

// ThreadRealtimeStartedNotification is a generated alias for a Codex app-server protocol type.
type ThreadRealtimeStartedNotification = SanitizedThreadRealtimeStartedNotificationJSON

// ThreadRealtimeTranscriptDeltaNotification is a generated alias for a Codex app-server protocol type.
type ThreadRealtimeTranscriptDeltaNotification = SanitizedThreadRealtimeTranscriptDeltaNotificationJSON

// ThreadRealtimeTranscriptDoneNotification is a generated alias for a Codex app-server protocol type.
type ThreadRealtimeTranscriptDoneNotification = SanitizedThreadRealtimeTranscriptDoneNotificationJSON

// ThreadSetNameResponse is a generated alias for a Codex app-server protocol type.
type ThreadSetNameResponse = SanitizedThreadSetNameResponseJSON

// ThreadShellCommandResponse is a generated alias for a Codex app-server protocol type.
type ThreadShellCommandResponse = SanitizedThreadShellCommandResponseJSON

// ThreadStatusChangedNotification is a generated alias for a Codex app-server protocol type.
type ThreadStatusChangedNotification = SanitizedThreadStatusChangedNotificationJSON

// ThreadTokenUsageUpdatedNotification is a generated alias for a Codex app-server protocol type.
type ThreadTokenUsageUpdatedNotification = SanitizedThreadTokenUsageUpdatedNotificationJSON

// ThreadUnarchivedNotification is a generated alias for a Codex app-server protocol type.
type ThreadUnarchivedNotification = SanitizedThreadUnarchivedNotificationJSON

// ThreadUnsubscribeResponse is a generated alias for a Codex app-server protocol type.
type ThreadUnsubscribeResponse = SanitizedThreadUnsubscribeResponseJSON

// TurnDiffUpdatedNotification is a generated alias for a Codex app-server protocol type.
type TurnDiffUpdatedNotification = SanitizedTurnDiffUpdatedNotificationJSON

// TurnInterruptResponse is a generated alias for a Codex app-server protocol type.
type TurnInterruptResponse = SanitizedTurnInterruptResponseJSON

// TurnModerationMetadataNotification is a generated alias for a Codex app-server protocol type.
type TurnModerationMetadataNotification = SanitizedTurnModerationMetadataNotificationJSON

// TurnPlanUpdatedNotification is a generated alias for a Codex app-server protocol type.
type TurnPlanUpdatedNotification = SanitizedTurnPlanUpdatedNotificationJSON

// TurnSteerResponse is a generated alias for a Codex app-server protocol type.
type TurnSteerResponse = SanitizedTurnSteerResponseJSON

// WarningNotification is a generated alias for a Codex app-server protocol type.
type WarningNotification = SanitizedWarningNotificationJSON

// WindowsSandboxReadinessResponse is a generated alias for a Codex app-server protocol type.
type WindowsSandboxReadinessResponse = SanitizedWindowsSandboxReadinessResponseJSON

// WindowsSandboxSetupCompletedNotification is a generated alias for a Codex app-server protocol type.
type WindowsSandboxSetupCompletedNotification = SanitizedWindowsSandboxSetupCompletedNotificationJSON

// WindowsSandboxSetupStartResponse is a generated alias for a Codex app-server protocol type.
type WindowsSandboxSetupStartResponse = SanitizedWindowsSandboxSetupStartResponseJSON

// WindowsWorldWritableWarningNotification is a generated alias for a Codex app-server protocol type.
type WindowsWorldWritableWarningNotification = SanitizedWindowsWorldWritableWarningNotificationJSON

// ClientNotification represents a generated Codex app-server protocol type.
type ClientNotification interface{}

// CodexAppServerProtocolV2 represents a generated Codex app-server protocol type.
type CodexAppServerProtocolV2 interface{}

// ConfigReadResponse represents a generated Codex app-server protocol type.
type ConfigReadResponse interface{}

// ConfigWriteResponse represents a generated Codex app-server protocol type.
type ConfigWriteResponse interface{}

// FsChangedNotification represents a generated Codex app-server protocol type.
type FsChangedNotification interface{}

// FsWatchResponse represents a generated Codex app-server protocol type.
type FsWatchResponse interface{}

// HookCompletedNotification represents a generated Codex app-server protocol type.
type HookCompletedNotification interface{}

// HookStartedNotification represents a generated Codex app-server protocol type.
type HookStartedNotification interface{}

// HooksListResponse represents a generated Codex app-server protocol type.
type HooksListResponse interface{}

// InitializeResponse represents a generated Codex app-server protocol type.
type InitializeResponse interface{}

// ItemGuardianApprovalReviewCompletedNotification represents a generated Codex app-server protocol type.
type ItemGuardianApprovalReviewCompletedNotification interface{}

// ItemGuardianApprovalReviewStartedNotification represents a generated Codex app-server protocol type.
type ItemGuardianApprovalReviewStartedNotification interface{}

// ItemStartedNotification represents a generated Codex app-server protocol type.
type ItemStartedNotification interface{}

// MarketplaceAddResponse represents a generated Codex app-server protocol type.
type MarketplaceAddResponse interface{}

// MarketplaceRemoveResponse represents a generated Codex app-server protocol type.
type MarketplaceRemoveResponse interface{}

// MarketplaceUpgradeResponse represents a generated Codex app-server protocol type.
type MarketplaceUpgradeResponse interface{}

// PluginInstalledResponse represents a generated Codex app-server protocol type.
type PluginInstalledResponse interface{}

// PluginListResponse represents a generated Codex app-server protocol type.
type PluginListResponse interface{}

// PluginReadResponse represents a generated Codex app-server protocol type.
type PluginReadResponse interface{}

// PluginShareCheckoutResponse represents a generated Codex app-server protocol type.
type PluginShareCheckoutResponse interface{}

// PluginShareListResponse represents a generated Codex app-server protocol type.
type PluginShareListResponse interface{}

// ReviewStartResponse represents a generated Codex app-server protocol type.
type ReviewStartResponse interface{}

// SkillsListResponse represents a generated Codex app-server protocol type.
type SkillsListResponse interface{}

// ThreadMetadataUpdateResponse represents a generated Codex app-server protocol type.
type ThreadMetadataUpdateResponse interface{}

// ThreadRollbackResponse represents a generated Codex app-server protocol type.
type ThreadRollbackResponse interface{}

// ThreadSettingsUpdatedNotification represents a generated Codex app-server protocol type.
type ThreadSettingsUpdatedNotification interface{}

// ThreadStartedNotification represents a generated Codex app-server protocol type.
type ThreadStartedNotification interface{}
