// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 3d2ee51ca2d5db578f328aa75e20aa22c0197c9a

package protocol

// GeneratedCodexCommit is the Codex source commit used to generate this protocol package.
const GeneratedCodexCommit = "3d2ee51ca2d5db578f328aa75e20aa22c0197c9a"

// GeneratedCodexVersion is the Codex package version used to generate this protocol package.
const GeneratedCodexVersion = "0.153.4"
