// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 25af12f7e61572b0bc18ddb1008be543b91519b0

package protocol

// GeneratedCodexCommit is the Codex source commit used to generate this protocol package.
const GeneratedCodexCommit = "25af12f7e61572b0bc18ddb1008be543b91519b0"

// GeneratedCodexVersion is the Codex package version used to generate this protocol package.
const GeneratedCodexVersion = "0.145.0"
