// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: 6b9826e3aa83b1a5947db50f4332cb9c65f1b340

package protocol

// GeneratedCodexCommit is the Codex source commit used to generate this protocol package.
const GeneratedCodexCommit = "6b9826e3aa83b1a5947db50f4332cb9c65f1b340"

// GeneratedCodexVersion is the Codex package version used to generate this protocol package.
const GeneratedCodexVersion = "0.154.0"
